### ISSUE TITLE
I have made an assumption and it's turned out to be..

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#1001]
FALSE!

I assumed the default for `notifyOnChangeProps` https://react-query.tanstack.com/reference/useQuery
```
Optional
If set, the component will only re-render if any of the listed properties change.
If set to ['data', 'error'] for example, the component will only re-render when the data or error properties change.
If set to "tracked", access to properties will be tracked, and the component will only re-render when one of the tracked properties change
```

was `"tracked"`.

It's not! it's undefined.

There's a PR to make it the default. But that was understandably, made for their v4 release as it is a breaking change.

What this means is when doing:

```
const { onHold } = useInboundFields("onHold")
```

I had assumed only a re-render when `onHold` changes. But this is not right. The selector *does* prevent re-renders from *other* data changing, however, since it is not using 'tracked' for `notifyOnChangeProps`, `isLoading` triggers re-renders.

Oh no!

So, because of this CARELESS assumption, will need to go through and check uses and add `tracked` in places. Starting with `useQuerySelector` - the main hook I had this assumption with

**Comment by joshxg** [comment]
Investigated a little bit. Just adding a couple of `notifyOnChangeProps: 'tracked'` to  couple of key places - `useQuerySelector` and `useOutbound`. I can't see any side effects which is good..

Profiling before hand - just opening the add item modal and then closing it on outbound shipment. It's not bad. ~40ms initial render, with ~9 renders of 40-60ms. It feels fine

With the small changes above, though:

![image](https://user-images.githubusercontent.com/35858975/157648504-1c3210d1-701e-4fc8-890d-fcaae7f41125.png)

There's 5 renders - less than 40ms, but there's no reason they should be less expensive, so I think best to assume no actual increase in individual render times, just less renders.

-------


I'm wondering if upgrading to the `react-query` alpha might be an option. Making `notifyOnChangeProps: "tracked"` the default 🤔 

Maybe I'll get in contact with the contributors and get a feeling for how stable it is?

**Comment by mark-prins** [comment]
I'd prefer not to rush in with v4-alpha yet, we can afford to wait a little longer for at least the beta release!
The `tracked` change made though sounds very promising - would be great to have that in.. and we can default to tracked when the release is out
