### ISSUE TITLE
Stocktake: Select items when creating

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1018]
Coming from [this comment](https://github.com/openmsupply/openmsupply-client/issues/582#issuecomment-1063524444) and that it is annoying to add one item at a time.

Could we show a list of stock items with a checkbox next to each and a 'select all' checkbox. 
On create, the stocktake is created and lines added for each selected item. Items can then be added and removed as they can now - no change to the edit / detail view

**Comment by joshxg** [comment]
This example is cool.. https://mui.com/components/autocomplete/#limit-tags

Though.. potentially 5,000 items on a site, so.. maybe not chips? 😁  🤷  Maybe it's too cool NOT to do it???

**Comment by mark-prins** [comment]
Too cool not to use somewhere!!

I'd want to have it `open` though, opening the autocomplete to pick an option is almost as bad as clicking the 'add item' button. and then it is like a list of options without a 'select all' option. that can be added though..
was just playing with the checkbox version.. pretty neat

**Comment by joshxg** [comment]
Very cool! Can use the same as the other `ListSearch` component and just use `open={true}` on the autocomplete 🤣
