### ISSUE TITLE
Outbound: Edit item

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1028]
Some tweaks have been requested

- [ ] wording changes
- [ ] reset quantity on pack size change

**Wording changes**
here, it should be: “Issue X units in packs of “Any”
![telegram-cloud-photo-size-4-5857026853104105720-y](https://user-images.githubusercontent.com/9192912/157802665-3a0d4ee8-ef52-45bd-9a25-e6832542a681.jpg)

here, it should say, issue X packs of X units
![telegram-cloud-photo-size-4-5857026853104105721-y](https://user-images.githubusercontent.com/9192912/157802710-d4b58334-6cbf-4a62-9451-1a102e779df0.jpg)

**Reset quantity**
"I think that quantity should be reset when changing the pack size
eg. First I issue 100 units in packs of “Any”
but then change my mind and decide to allocate in packs of 10
quantity should not be 100 anymore otherwise I would allocate 1000 units
either system can automatically update to 10 pack of 10
or reset to 0"

**Comment by joshxg** [comment]
Also tax and line total columns? Tax blocked by `StockLineNode` tax?
