### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1029]
Functionality needs reviewing - I _think_ that it isn't refreshing and/or isn't timing users out when the cookie expires.
Would like to test the functionality and maybe, who knows, fix it? If broken.

**Comment by joshxg** [comment]
react query docs, maybe helpful?

```
refetchIntervalInBackground: boolean
Optional
If set to true, queries that are set to continuously refetch with a refetchInterval will continue to refetch while their tab/window is in the background
```

**Comment by CarlosNZ** [comment]
When the refresh runs (I just set it to 30 seconds for testing), this is the current response:
```
{
  "data": {
    "refreshToken": {
      "__typename": "RefreshTokenError",
      "error": {
        "description": "No refresh token provided",
        "__typename": "NoRefreshTokenProvided"
      }
    }
  }
}
```

**Comment by mark-prins** [comment]
you'll get that locally, and when running against the demo server. The only accurate check is when on the demo server.. that was refreshing initially.. it was the subsequent refreshes that weren't happening..

The refresh token is stored in an http-only cookie. I had to test using thunder client / postman to get the refresh response working.

- local: there's a bug in the api which means that `Secure` is set when there is no local cert - and I was unable to trust a self signed cert enough to get it to work with SSL.
- remote: the domain differs 🙄 


The issue with the refresh on demo is that I'm not being logged out automatically due to inactivity, and that the refresh isn't happening when in the background ( I think ).

**Comment by CarlosNZ** [comment]
One thing I noticed that might be worth improving -- when the timer does log you out, there's no indication in the UI that this has happened. So when you next click on something that performs a query, you just get a query error and its not clear why. Until you refresh the page and then realise you're logged out.

Do you think we should have it automatically navigate back to the login screen when a timeout occurs?

**Comment by mark-prins** [comment]
yeah - that's what I was hoping for. currently that requires a refresh, simply navigating doesn't initiate anything. Will see what can be done.

there was this in the designs originally, though we haven't discussed any functionality like this 

![Screen Shot 2022-03-16 at 11 52 33 AM](https://user-images.githubusercontent.com/9192912/158485435-9571be9f-fda2-40c7-aeb0-ecb4e890776e.png)
