### ISSUE TITLE
response column already issued should use the requested quantity

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#1036]
currently using 

```
accessor: ({ rowData }) =>
          rowData.supplyQuantity - rowData.remainingQuantityToSupply,
```

This means that when you change the supply quantity, the 'already issued' changes which seems odd to me. The amount that has been issued should be the quantity the user requested minus the quantity remaining to supply and not change while editing the requisition itself

**Comment by joshxg** [comment]
I think this change should happen, but it's hardto test and check with the API in its current form as there is a bug with `remainingQuantityToSupply` which is giving back incorrect values
