### ISSUE TITLE
Set response supplied to requested

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#1055]
from https://github.com/openmsupply/openmsupply-client/issues/100

> Set automatically set the quantity to be supplied for every line to be equal to the requested quantity.

- Can be an action in the drop down bulk actions
- Just use the batch update mutation. A specific mutation would be better in the future

**Comment by joshxg** [comment]
Oh! There's no batch mutation for a response, oops!

But there is a mutation `useSuggestedQuantity`! Though it does use all of the lines and not individual ones. Will add an app bar button for it.

**Comment by joshxg** [comment]
Silly silly me.

The title: set *requested* to *suggested* in response reqs
The requirement: set the *supplied* to the *requested* in response reqs
the mutation: `useSuggestedQuantity`

<src img="https://media1.giphy.com/media/13LlAxmDwAkopO/200.gif?cid=5a38a5a2noec9gbf7temckknhurkb056pwhitw0fcg725gqw&rid=200.gif&ct=g"/>

**Comment by joshxg** [comment]
And now I've just tried to implement this with using `Promise.all` and an array of update promises. This makes sqlite become locked and unusable and also sometimes has internal errors for some of the lines with a non-useful message.

I'm giving up!

**Comment by mark-prins** [comment]
😢

**Comment by andreievg** [comment]
Fyi

There is supplyRequestedQuantity: https://github.com/openmsupply/remote-server/issues/942

And https://github.com/openmsupply/remote-server/issues/841 to fix sqlite concurrency

**Comment by joshxg** [comment]
There is supplyRequestedQuantity: https://github.com/openmsupply/remote-server/issues/942 🤣  🤣  🤣 

Whats wrong with me?!
