### ISSUE TITLE
Organise package api/hooks better

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#1063]
The api/hooks files in each of the packages are generally pretty packed and a bit difficult to grok. 

Would be good to make it simpler to read and find what you're looking for. Also would be great to not have to import so many individual hooks 😁 

Some options:

### Individual files for each hook

- Can likely pair this with a test file in the future which would be nice ✅ 
- A lot of files ❌
- can search file names easily with an ide ✅ 

### Partition by functionality
- `mutations` v `queries` / `query` v `update` v `insert` 
-  not as many files ✅ 
-  hooks that do more than one thing confusion ❌
- Can search by functionality easily ✅ 

### Partition by entity
- `document` v `lines` i.e invoice v invoice lines
-  not as many files ✅ 
-  hooks that do more than one thing confusion ❌
- Can search by 'feature' easily ✅ 

### Combo
- Individual files ✅ 
- Name space object to consolidate - end up with an api like `useOutbound.document.insert()`, `useOutbound.line.update()` - i like name spacing obvs ✅ 
- Could structure the files in `hooks/lines` to get search by feature ✅ 

### Do nothing
- It's fiiiine

I like combo, what do you like? @mark-prins @CarlosNZ

**Comment by mark-prins** [comment]
you've done a good job on selling the combo 😁 
I'm just not sure what it looks like! when you say 'individual files' how does that work in practice? not having each hook in a sep. file obvs.. or we are back at option 1.
The name space partitioning is pretty neat, and covers what we have with `useOutboundLine` etc in a nice consistent way.

**Comment by joshxg** [comment]
Bias much?

For the combo I did mean individual files for all the hooks so that cmd+p can easily pick the hooks up and navigate to them, but also get the benefit easy imports.... 🤔 

Something like:
- `outbound/api/hooks/document`
    - `useOutboundUpdate.tsx`
    - `useOutboundDelete.tsx`
    - ...
    - `index.ts`
    - `OutboundDocumentHooks.ts` - consolidate and export as a single object
- `outbound/api/hooks/lines`
    - `useUpdateLines.tsx`
    - `useDeleteLines.tsx`
    - ...
    - `index.ts`
    - `OutboundLineHooks.ts` - consolidate and export as a single object
- `outbound/api/hooks`
    - `OutboundHooks.ts` - consolidate the single objects from document/lines as a single export
    - `index.ts`

Resulting in the next iteration of what I think looks nice...

```
import {useOutbound} from './api'

useOutbound.document.get.detail()
useOutbound.document.get.list()
useOutbound.document.update()
useOutbound.document.delete()
useOutbound.document.deleteMany()
useOutbound.line.lines() // ew? Lines v items v rows 🙄 - line is the actual entities, items the aggregate, row is whichever is selected
useOutbound.line.items() 
useOutbound.line.updateMany()
useOutbound.line.deleteMany()
```
