### ISSUE TITLE
Spinning man logo has wrong BG color on hover

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1074]
Just a tiny thing:

<img width="235" alt="Screen Shot 2022-03-17 at 10 43 25 PM" src="https://user-images.githubusercontent.com/5456533/158781950-eabf2840-a7b4-4501-95bc-e4454db8b081.png">

**Comment by mark-prins** [comment]
that's because it's a button and that's the material ui style on it.
I think it's fine - but maybe that's because I know its a button.. perhaps you'd like to see if it can be changed 😁
