### ISSUE TITLE
Remove suggestedQuantity calculation

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1084]
Ref: [This comment](https://github.com/openmsupply/openmsupply-client/issues/1070#issuecomment-1069772173)

the calculation isn't required now, so we can remove the usage and change to api, now that the value is being returned.
Can probably remove the calculation as well to avoid confusion later.

**Comment by mark-prins** [comment]
@CarlosNZ where did you get to with this? can we just close it?

**Comment by CarlosNZ** [comment]
Yes, let's. I don't think there's much more we can do with it at this stage.
