### ISSUE TITLE
Remove organisation selector from login screen

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1098]
For now, we will just use the store switcher at the bottom of the app page. Eventually, this will be restricted to a list of *allowed* stores, not the full list.

When logging in the user should be automatically logged in with their most recently used store (in localStorage).

**Comment by mark-prins** [comment]
will require some changes in the API - a list of stores for a user (or all users?)
perhaps the login should return the default or most recently used store, and maybe a list of stores which the user has permission to use?

**Comment by mark-prins** [comment]
oops, had the wrong issue in the PR. Store has been removed, so will close this one.
