### ISSUE TITLE
Give better feedback about database errors

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1101]
Currently, if there is a database error when making a query the UI shows "No records to display". This could be misleading -- user thinks there are no items when there was actually a database problem. 

We should probably catch database errors more specifically and actually display some kind of error alert to the user.

**Comment by mark-prins** [comment]
Had created a new issue with the following comment.. but had intended that the changes be done on this issue.

Following on from #1113 - that one has added a global error catch in the graphql request implementation.

There's also an error handling change in #1125 which throws an error in the GqlContext when the response has an error, which allows graphql-request to respond in the `onError` callback. That part could be lifted out into an error boundary and use notistack to toast on error as a general handler for error objects being returned.

Would be nice to make use of different levels of error boundaries in graphql-request, such as noted in [this comment](https://github.com/openmsupply/openmsupply-client/pull/1113#issuecomment-1078748253) and respond differently given the severity of the problem
