### ISSUE TITLE
New outbound shipment

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#112]
- Add a button on the outbound shipment page for creating a new outbound shipment
- Send a request to the server to create the shipment record which is then returned with details filled - i.e. status, dates
    - We will need 'create `OS`' style method in the backend which we'll basically need to keep in sync with the frontend otherwise.
- Create the outbound in memory and set the query cache to be equal to the in memory outbound.
- Both of these options would be better if the id was created client side 🤔 
- unsure which is better. Think the first

**Comment by joshxg** [comment]
Not a huge amount of code to create records, generally. Using mobile as the example: https://github.com/openmsupply/mobile/blob/master/src/database/utilities/createRecord.js

Some reasons to do "create on server":
- Mobile doesn't have plugins/as many preferences which cause more logic in the creation process and more duplicated code.
- Serial numbers are a bit annoying. If we don't create first: display: `#?`?

Con of creating on the server first would be that we might have outbounds with no related `name` which is generally not possible
- Could set a default.. 
- Could use a wizard to select the name beforehand 🤣

**Comment by mark-prins** [comment]
are you thinking to create before any client populating? click the button -> create on server -> show user a blank page where they then select the `name`. that kind of thing?
If so, could we wait until a `name` is selected and create then?

**Comment by joshxg** [comment]
Yeah. I am hoping we make the flow of creating as close to editing as possible.

Can see how much the difference really is while implementing between the options I reckon. But I'm not really understanding what we are preventing by not allowing a shipment to be made without a name. Users who are intentionally making a bunch of blank invoices (which aren't harming anything)?

**Comment by joshxg** [comment]
Couple other considerations:

- URL is currently `customer-invoice/:id` (will change) - I *think* linking to an invoice is good? Would be nice to be able to have more readable ids - so using the invoice number?
- If not creating beforehand I'm not sure what to do about the URL - `/new`? Then once saved, do we update to be the real id/invoice number or leave it as `new`?

**Comment by mark-prins** [comment]
ah, right. yes - agree, that sounds much nicer.
All good with creating blank entities then, and using the invoice number in the URL rather than a mystic guid

**Comment by joshxg** [comment]
reference pictures:

![image](https://user-images.githubusercontent.com/35858975/131943060-27a34ac8-d339-4c30-97e1-a9eb7786ec2d.png)


![image](https://user-images.githubusercontent.com/35858975/131943251-1d55548b-252c-4a19-8997-f98606bc9743.png)



I think the second is what we're going for. So will add the button for a new shipment into the toolbar above

**Comment by joshxg** [comment]
Think I have a nice way of getting what I think is the best of both worlds.

- Clicking `new` goes to `/new` and creates a transaction in memory
- When saved, if the invoice hadn't been previously persisted, change the url to the invoice number returned without reloading the page
- Could make this auto-save after selecting a customer, if that's good, or just leave it
