### ISSUE TITLE
Enable fallback translations

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#113]
- Don't want to add new strings to every json file every time
- Enable some sort of fallback when translations don't exist
- Update the type to allow for keys only being within the english json
- throw an error if the key doesn't exist in the english json?

**Comment by mark-prins** [comment]
The main issue I had when trying to implement was not loading in the default language file (en) as well as the current language file while keeping the type checking of allowable keys

**Comment by joshxg** [comment]
Yeah. Had a quick play. Basically the same conclusion

- Can do a fallback and have the `key` displayed, rather than the english variant. Pretty iffy
- Could bring the english defaults in during development then would need to make it a build step to 'fill out' all the jsons
- Just bring in english also 🤣
