### ISSUE TITLE
Supplier and Customer detail: mock data implementation

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1130]
With some mock data available we can put in a placeholder for the name detail pages.
There's no design mockup, so just make something that looks ok.

Here's what mSupply looks like, for reference:

![Screen Shot 2022-03-30 at 8 14 18 AM](https://user-images.githubusercontent.com/9192912/160689790-5f84674d-6188-4fe7-88a5-509f239ab1e7.png)

The item detail page is the closest we have - though for names we don't have stats and so is a simpler page. Perhaps for this one, just a detail modal rather than a full page. At least for now while there aren't many fields available and the fields are all read-only

**Comment by CarlosNZ** [comment]
I can have a crack this one.

Should we do tabs?

And in terms of what fields to show -- just use what's available for the query endpoint?
