### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1132]
@richardmoizeau has picked up a few things while creating documentation. There will be more coming.. this is just a place to pop in the ones found so far and to knock off a few at a time rather than creating a single issue per item

- [x] `Cancel` buttons - in the detail views the 'cancel' doesn't actually cancel it just returns you to the list. The name should be 'Close' or 'Return to List' or 🤷 
- [x] Shipments > it is not clear that you should enter a % for tax rate
- [x] Shipments > List: Invnum should be replaced by Shipment ID or Shipment Number
- [x] Shipments > List: Customer column is too wide
- [x] Shipment > List: Customer to be replaced by Customer Name
- [x] Shipment > List: Entered should be replaced by Entered on or Created on 
- [x] Shipments > List: Total should be replaced by Total Value
- [x] Shipments > List: add Customer Ref
- [ ] Shipment > List: would it be possible to have the below item always at the bottom of the page ?
![Screen Shot 2022-03-30 at 2 28 26 PM](https://user-images.githubusercontent.com/74992958/160732654-68a6caaa-fd34-407e-ba41-0c67ff70c664.png)
- [x] Shipment > List: cannot navigate to another page if I'm not at the bottom of the list (using vertical scroll bar). It seems that the issue is only with the 'last page'. When clicking on it, it is activating the main check box
- [x] Shipment: no warning dialog when deleting selected lines (bulk actions)
- [ ] O/Shipment: created a line for an item with no stock (placeholder). When I use the "Allocate Placeholder Lines" function, notification says 1 line has been allocated but in fact... no :) Suggestion for notif: 
```
Allocated X line (when line has been fully allocated)
Partially allocated X line (when line has been partially allocated)
X lines not allocated 
```
- [ ] O/Shipment: when I try to confirm allocation with unallocated line, I get the dialog. When I click on `OK`, I'm redirected to the login page
- [ ] when i try to delete a line when status is "shipped", notif says "no you can't unless it's new" but actually you can delete line when status is allocated or picked. Suggestion: You cannot delete a line when status is shipped. 
- [ ]

**Comment by mark-prins** [comment]
> Shipment > List: would it be possible to have the below item always at the bottom of the page ?

There was #360 I actually think it is better to have the pagination next to the table, not stuck at the bottom of the page. 

> Shipment: no warning dialog when deleting selected lines (bulk actions) 

This will be handled in #1115

**Comment by mark-prins** [comment]
>  Shipments > List: Customer column is too wide

Have removed the width restriction which was on the comment column, which fixes the layout for smaller screens. If the comment is small or the screen very wide, then the name column is still fairly wide. The only reliable way to resolve that is to restrict the name column width and I think it is better to have it responsive.

**Comment by mark-prins** [comment]
> Shipments > List: Invnum should be replaced by Shipment ID or Shipment Number
> Shipment > List: Customer to be replaced by Customer Name
> Shipment > List: Entered should be replaced by Entered on or Created on
> Shipments > List: Total should be replaced by Total Value

Have added a tooltip for these - changing to long column names will make the columns wider and/or split over two lines which looks terrible.

**Comment by richardmoizeau** [comment]
> split over two lines which looks terrible
Yes I agree. Hate it too. I'm a bit scared for the french though which is usually longer than english...
