### ISSUE TITLE
Determine locale by system setting

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1150]
This will need some investigation to see whether it's worth it. 

~~Consider using this package: https://www.npmjs.com/package/os-locale~~
Actually, this one seems more promising: https://www.npmjs.com/package/get-user-locale
Or, more specific to our i18n library: https://www.npmjs.com/package/i18next-browser-languagedetector

If it's reliable, then we should also try and use the os locale as the default language (rather than just assuming English)

**Comment by jmbrunskill** [comment]
Don't you already have the locale from i18next-browser-languagedetector?

This blog seems to imply you could use the detected language with the JS built in Intl.DateTimeFormat function
https://phrase.com/blog/posts/localizing-react-apps-with-i18next/#Date_Formatting

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

Not sure if that helps (haven't tried any of this!)

**Comment by CarlosNZ** [comment]
Thanks @jmbrunskill, yes we should be able to use i18next-browser-languagedetector. Will add it to the original post.

Cheers.
