### ISSUE TITLE
Usability issues: episode 2

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/openmsupply-client#1169]
# Outbound Shipment

- [x] O/Shipment: created a line for an item with no stock (placeholder). When I use the "Allocate Placeholder Lines" function, notification says 1 line has been allocated but in fact... no :) Suggestion for notif: 
```
Allocated X line (when line has been fully allocated)
Partially allocated X line (when line has been partially allocated)
X lines not allocated 
```
- [x] when i try to delete a line when status is "shipped", notif says "no you can't unless it's new" but actually you can delete line when status is allocated or picked. Suggestion: You cannot delete a line when status is shipped. 
- [x] O/Shipment: On large screen, OS list do not take the full width of the screen

# Inbound Shipment

- [x] I/Shipment: when deleting, notification says 'Invoice' instead of 'shipment

# Internal Order

## Internal Order's List

- [x] `New Requisition` Button: should be `New Order` ?
- [x] `Search by comment...`: maybe more useful to look by supplier name or status ? (Waiting for a complex search in future releases). 
- [x] Internal order list: add `Created on` 
- ~sorting list with column headers: no way to cancel sorting except if you refresh the page.~
- [x] when deleting, notification says `Deleted X requisition(s)`, should be `Deleted X order(s)`
- ~`Export` button: bulk action ?~

###  Internal Order Headers

- ~`Requested to Suggested` could be a bulk action (`Actions` dropdown)~
- [x] `Supplier Ref` should be `Reference` or `Order Reference`
- [x] No need to skip status for Internal Orders
![Screen Shot 2022-04-08 at 2 25 20 PM](https://user-images.githubusercontent.com/74992958/162350927-2e658df0-736a-4b70-a45b-54a6a563afb2.png)

###  Internal Order Information Panel

- [x] Missing additional info: `Created on`, `Last modified on`, `Last modified by`

### Order line modal

- [x] Internal Orders > Consumption History chart: orange datapoint should be "AMC", not "Req. Qty." (an error from Manu's preview)

![Screen Shot 2022-04-07 at 4 36 48 PM](https://user-images.githubusercontent.com/74992958/162121061-bba4d392-ca23-4a79-9170-a6fc3cd5e48c.png)

- [x] Remove stocks details & Order title. Keep the one for Comment (and if not too long, put the comment on the right)
- [x] Internal Orders > Charts: Could we add SOH under AMC ?
![Screen Shot 2022-04-07 at 4 38 48 PM](https://user-images.githubusercontent.com/74992958/162121295-f9858951-80eb-4d09-9b00-1d8fbf41a4ec.png)
- [x] Internal Orders > Charts: Stock Distribution is not a correct title. Maybe no title at all ?  
![Screen Shot 2022-04-07 at 4 41 13 PM](https://user-images.githubusercontent.com/74992958/162121576-4f0fdf10-ec82-478d-8a2f-9b7f8d6fce8a.png)

**Comment by mark-prins** [comment]
First item (allocation) - the server does not tell us if there was a problem. This is what is returned when I allocate a line which has no stock:

```
 "allocateOutboundShipmentUnallocatedLines": [
                {
                    "id": "c5c5acb5-d19d-4850-9466-f9348bc7d14b",
                    "response": {
                        "__typename": "AllocateOutboundShipmentUnallocatedLineNode",
                        "deletes": [],
                        "inserts": {
                            "totalCount": 0
                        },
                        "updates": {
                            "totalCount": 1
                        }
                    }
                }
            ]
```

Will see if I can determine allocation status based on the full invoice response.

**Comment by mark-prins** [comment]
> O/Shipment: when I try to confirm allocation with unallocated line, I get the dialog. When I click on OK, I'm redirected to the login page

@richardmoizeau I cannot recreate this one. perhaps you could show me?

**Comment by mark-prins** [comment]
> sorting list with column headers: no way to cancel sorting except if you refresh the page

The list is sorted by name initially, and the list must be sorted by something!

**Comment by mark-prins** [comment]
> Internal order list: add Created on

There is already a created column 😕

**Comment by mark-prins** [comment]
> Export button: bulk action ?

The intention was to export the list, I think. Tried removing it, since it doesn't do anything, but the page looks funny without it, so put it back in 🤷

**Comment by mark-prins** [comment]
> Requested to Suggested could be a bulk action (Actions dropdown)

No, not currently. There is only functionality in the API for this to happen for the whole invoice.

**Comment by richardmoizeau** [comment]
> > Internal order list: add Created on
> 
> There is already a created column 😕

Maybe it is just because I don't have the latest version on the demo. 

<img width="1337" alt="Screen Shot 2022-04-08 at 4 47 27 PM" src="https://user-images.githubusercontent.com/74992958/162366290-e8c5179f-33a3-44b2-aa2a-bc185af106f0.png">

**Comment by richardmoizeau** [comment]
>

**Comment by richardmoizeau** [comment]
> > O/Shipment: when I try to confirm allocation with unallocated line, I get the dialog. When I click on OK, I'm redirected to the login page
> 
> @richardmoizeau I cannot recreate this one. perhaps you could show me?

I can't replicate it either. So I think we're good.

**Comment by mark-prins** [comment]
> Maybe it is just because I don't have the latest version on the demo.

Maybe it's because I was looking at Outbounds 🙄

**Comment by mark-prins** [comment]
> Missing additional info: Created on, Last modified on, Last modified by

Unfortunately, this isn't available in the API. I've created an issue for the team to add more details.
We only have `created by` and `created on`. The API doesn't track who last modified, or when.
