### ISSUE TITLE
Logged out > logged in > logged out

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#1171]
After being logged out, the logged out alert is showing immediately after logging in. A refresh of the browser clears the problem

<img width="671" alt="Screen Shot 2022-04-08 at 10 19 13 AM" src="https://user-images.githubusercontent.com/9192912/162328980-e445081e-d3df-40bf-ae16-09b55917276f.png">

**Comment by CarlosNZ** [comment]
Might be a bit aggressive, but when logging out it might be an idea to just use `window.location.href = '/login'`. This basically forces a reload and so resets all React state, etc.

We don't want to cause a full re-download of the app though, but I'm fairly sure it'll just use the cache.

**Comment by mark-prins** [comment]
oh nice! that's a good idea and should work around the problem 😁 

I've been looking into it, and so far cannot reproduce without having `refreshToken` bomb out, which it will do in local dev. I've configured https://demo-open.msupply.org:88 ( you have to be on the server, as it tries to server the assets on localhost ) with a 2 minute timeout and that is working fine, with the refresh token refreshing. 

I think there's another issue which is resetting the auth cookie, just trying to find that

**Comment by mark-prins** [comment]
I believe this is the `refreshToken` query. 
We send:

![Screen Shot 2022-04-08 at 12 06 15 PM](https://user-images.githubusercontent.com/9192912/162339042-928644b9-6c5c-4ede-8e00-8a893b436401.png)


and receive:
```
{
    "data": {
        "refreshToken": {
            "__typename": "RefreshTokenError",
            "error": {
                "description": "No refresh token provided",
                "__typename": "NoRefreshTokenProvided"
            }
        }
    }
}
```

there is a token being sent - though in the example given there is a rogue cookie (`-`) which perhaps is not being interpreted correctly by the server? Clearing that cookie and all works ok.

Have been unable to cause the issue any other way.

**Comment by mark-prins** [comment]
Closing for now - unable to replicate
