### ISSUE TITLE
Usability Issues Episode 4

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/openmsupply-client#1181]
### Delete a location

- [ ] It seem logical that you should be able to delete a location from another store, but why do you see it in the 1st place ? :)
<img width="428" alt="Screen Shot 2022-04-12 at 4 58 30 PM" src="https://user-images.githubusercontent.com/74992958/162883856-62ac8bdb-ca1b-482b-94a8-9f823a1c77bc.png">

- [x] Select > Delete lines: should be delete selected lines ?

## Stock

- [x] Rename the menu => `View Stock` 

## Stocktake

- [ ] Stocktake or Stock take ;)

### Stock take: Edit Item

- [x] Similar to Inbound Shipment, tab shortcut won't work for french keyboards (AZERTY). Shift + 1 on the french KB will give you `1`. So if somebody is typing 1, 2 or 3, system would change tabs instead of writing 1
- [x] Item code appears twice:
<img width="579" alt="Screen Shot 2022-04-12 at 6 42 30 PM" src="https://user-images.githubusercontent.com/74992958/162897204-08a51ff8-9133-491f-ba93-46f2aa464cd0.png">

- [ ] Add batch button:  + icon appears twice: 

<img width="176" alt="Screen Shot 2022-04-12 at 6 45 31 PM" src="https://user-images.githubusercontent.com/74992958/162897618-7aa1ada7-7882-4266-8f09-0b36a57b1d68.png">

### Stock take: Add item
- [x] item is not added when using `Add Item` button

**Comment by mark-prins** [comment]
Delete location: have raised an issue for the API: https://github.com/openmsupply/remote-server/issues/1027
The problem is that the list of locations returned does not restrict by store, even though this is supplied.
