### ISSUE TITLE
internal orders: modal for editing a line doesn't pick up the suggested quantity

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/openmsupply-client#1184]
As per 1. & 2. in attached image. Thanks.
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/254026/163705336-000684a6-16e7-4176-b38d-61bda55afc4e.png">

**Comment by mark-prins** [comment]
That would have to be [internal order 13](https://demo-open.msupply.org/replenishment/internal-order/13) in Opua

the modal is simply showing the value returned by the API: 

![Screen Shot 2022-04-19 at 8 48 35 AM](https://user-images.githubusercontent.com/9192912/163875662-508dcefa-dbc0-45fe-9f33-88bcd8a74939.png)

I noticed the same last week and raised an issue: https://github.com/openmsupply/remote-server/issues/1022
On investigating, I determined that creating a new internal order, when there was historical data, did calculate correctly. Couldn't see any issues in the API either. This requisition is likely one that I created in the database - it's useful to have data to work with, and would have done that prior to the AMC fields existing.

I've updated the data directly for the requisitions which have amc and no suggested quantity.
Can I close this issue?
