### ISSUE TITLE
Server sync config

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/openmsupply-client#1193]
This PR (https://github.com/openmsupply/remote-server/pull/1044
) contains all required changes to do the initial sync config, e.g. config sync settings and restart the server:

The new api can also be used to figure out if the server is running normally or if it is in "stage0" config mode. In stage0 mode no bearer token is needed.

The server config and the restart endpoints are the same in both modes, e.g. same schema could be used...

For example,  when starting the client:
- Check if server is in stage0 mode and show a config screen to update sync settings and restart the server
- In normal mode the same config screen could be used to update the settings and restart the server.

**Comment by mark-prins** [comment]
Tasks for this issue:
- update api client to get the new methods
- add sync config to admin area
  - after a successful save, restart the server
- add restart server button?
- checkbox for restart on save?
