### ISSUE TITLE
Authentication Error !!!

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/openmsupply-client#1197]
On a Central server, Intentionally did not kept the sync user details correct inside `configuration ->> base.yaml`.
Started remote server using `cargo run` although the `omsupply-database` was introduced which then failed to push the records onto the remote server, end result was something like that:

` Caused by:│@openmsupply-client/host:   ../config/src/index.ts 2.54 KiB [built] [code generated] HTTP status client error (401 Unauthorized) for url (http://localhost:2048/sync/│@openmsupply-client/host:   ../config/src/routes.ts 2.41 KiB [built] [code generated] v5/queued_records?limit=500)`

The 4d Primary server was running, with the frontend, Authenticated with the valid username and password, that got authenticated correctly takes inside the frontend with saying `Authentication Error !!!`

Hope this make sense to describe the issue i am seeing.

[Authentication Error Video](https://www.dropbox.com/s/m5rd3xuvzafsj7x/openmSupply%20issue%20authentication.mp4?dl=0)

**Comment by mark-prins** [comment]
The error that is shown in the toast says 'Missing access to store' - that's the response from the server and indicates exactly that: the user is authenticated but you are logged in to a store that you don't have access to.

I'm not sure what you want me to change! as far as I can see, you have a user with no permission and a prompt is shown saying 'permission denied'. what else would be helpful here?

Perhaps if you could send the database? Given that this is a data issue I may have trouble recreating what you are seeing

Two things I can see which could be addressed
1. In the f/e there are additional errors when trying to destructure responses from the server, which are undefined when you have no permission. the ones in the video are:
- customer requisitions `cannot read properties of undefined (reading 'requisitions')`
- inbound shipments `cannot read properties of undefined (reading 'invoices')`
- master lists `cannot read properties of undefined (reading 'masterLists')`

2. the error raised by the server when pushing records - would need to raise that in the remote-server repo. I'll have to discuss with the team first though

**Comment by craigdrown** [comment]
Thanks @mark-prins  - will close.

**Comment by bijaySussol** [comment]
> Perhaps if you could send the database? Given that this is a data issue I may have trouble recreating what you are seeing

https://www.dropbox.com/s/qssf06qyipu6j50/Sqlite-remote-server.zip?dl=1

> The error that is shown in the toast says 'Missing access to store' - that's the response from the server and indicates exactly that: the user is authenticated but you are logged in to a store that you don't have access to.
> 
> I'm not sure what you want me to change! as far as I can see, you have a user with no permission and a prompt is shown saying 'permission denied'. what else would be helpful here?
> 
> Two things I can see which could be addressed
> 
> 1. In the f/e there are additional errors when trying to destructure responses from the server, which are undefined when you have no permission. the ones in the video are:
> 
> * customer requisitions `cannot read properties of undefined (reading 'requisitions')`
> * inbound shipments `cannot read properties of undefined (reading 'invoices')`
> * master lists `cannot read properties of undefined (reading 'masterLists')`
> 
> 2. the error raised by the server when pushing records - would need to raise that in the remote-server repo. I'll have to discuss with the team first though

How this looks like the web client  is directly connected to the Central server not to the remote server.
Is not this should be : Web app -> remote server -> Central server?

Now what this shows is, If there is something wrong on remote-server records like in this case it does not have user_permission / user_store_join, but has user, It get authenticated fine (I am not sure what other checks are on remote server) then it let you IN and then when it reached to the Dashboard page of web client, there it seems like a check is been done so remote server did not found an of the details and started saying: `Authentication Error`

But is not that should have allowed in a first place that is while logging in from Web client @mark-prins?

so, It looks to me, there is some error or check missing on remote server which allowed to login into when there is no proper join or permission? Maybe this should be an issue with remote server over a web client?

**Comment by mark-prins** [comment]
Thanks Bijay! 
Just to confirm - the web app only connects to the remote-server, it does not authenticate against central server at all.
Have raised https://github.com/openmsupply/remote-server/issues/1061 as I think the remote-server should not be allowing the user to log in

**Comment by bijaySussol** [comment]
> Thanks Bijay! Just to confirm - the web app only connects to the remote-server, it does not authenticate against central server directly. Have raised [openmsupply/remote-server#1061](https://github.com/openmsupply/remote-server/issues/1061) as I think the remote-server should not be allowing the user to log in

Thank you for confirming that
