### ISSUE TITLE
Outbound Shipment: Invalid value for argument

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/openmsupply-client#1201]
Creating a new outbound shipment, issuing with a small quantity instance 0.5, It complained saying, `Invalid value for argument`.

### Steps to reproduce:

- Setup a remote server, Web client and Central server
- Once setup is completed, Login
- Click to create a new `Outbound shipment`
- Select the item having SOH > 0
- On a issued batch line, enter quantity with 0.5
- Click OK
- See the message

<img width="744" alt="Screen Shot 2022-04-29 at 11 00 35 AM" src="https://user-images.githubusercontent.com/13144882/165888738-fb2d147a-5067-43ae-bc8a-dc1636143ccd.png">

**Comment by mark-prins** [comment]
Fixed with #1202
