### ISSUE TITLE
Cannot delete the Outbound shipment

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/openmsupply-client#1204]
### Step to reproduce

- Setup remote-server, Central server, Web-client
- Login to Web-client
- Create a dummy Outpatient invoice, add a line then delete the line save it
- View the Outpatient list
- Find that Outpatient shipment
- Select it and click `Delete selected lines`  from the option DDL
- It asked to `Select the line / lines`, but is already selected

<img width="1430" alt="Screen Shot 2022-04-29 at 1 45 54 PM" src="https://user-images.githubusercontent.com/13144882/165906210-1a829b4b-eff4-4d8e-8454-837144cc80f9.png">

**Comment by mark-prins** [comment]
unable to reproduce this one. Followed the steps above, and the invoice was deleted 🤷

**Comment by mark-prins** [comment]
have reproduced! 😁 details to follow when I've investigated a little more
