### ISSUE TITLE
Inbound shipment: Doubles up the stock line leading ledger problem

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/openmsupply-client#1206]
### Steps to reproduce:

- Created new item from Central server
- Synced fine, Made it to remote server, got it available for web client
- From Web client, Click on `Replenishment -> Inbound Shipment`
- Create a new Inbound Shipment clicking `New Shipment`
- Give the batch line
   - Added 2 batch line with Location, Sell price, Expiry, Batch information
- Once details are filled in, Verify it
- Wait to make this available on Central server
- Check that item > Stock line
- You will see stock line been double up and do a ledger check
   - Will see a ledger problem

 [open-msupply-client-ledger-problem Video](https://www.dropbox.com/s/cev5k8ln1huni1m/open-msupply-client-ledger-problem.mp4?dl=0)

### Images:

<details>

#### On SQL database

<img width="1051" alt="Screen Shot 2022-04-29 at 5 15 23 PM" src="https://user-images.githubusercontent.com/13144882/165936419-78958e49-0cb7-482f-941a-2103bc5e107a.png">

#### On Web client

<img width="1200" alt="Screen Shot 2022-04-29 at 5 16 17 PM" src="https://user-images.githubusercontent.com/13144882/165936498-e4a702aa-1de3-4790-954e-729b1d07e31f.png">

#### On Web client -> View stock

<img width="1196" alt="Screen Shot 2022-04-29 at 5 25 45 PM" src="https://user-images.githubusercontent.com/13144882/165937811-321a7e3b-4999-4e92-8857-823a19f182ac.png">

#### On Central server

<img width="1277" alt="Screen Shot 2022-04-29 at 5 17 09 PM" src="https://user-images.githubusercontent.com/13144882/165936700-6acf022b-5b55-42aa-9be3-eebc45302ca9.png">

</details>

**Comment by mark-prins** [comment]
Not an issue with the f/e and possibly not with the remote-server, though I don't have time to investigate that. you could try raising an issue in the remote-server repo - though it would appear to be a sync issue and would have to be resolved in the mSupply repo.

Looking at the mutations - there is a request to create only two inbound shipment lines, and the result is only two lines in the remote-server database:

![Screen Shot 2022-05-02 at 12 25 30 PM](https://user-images.githubusercontent.com/9192912/166171157-2ba00424-ac59-44d6-b2e7-0029fcf612b7.png)

However, mSupply creates two [`invoice_line`] records and only two [`item_line`] records

![Screen Shot 2022-05-02 at 12 25 48 PM](https://user-images.githubusercontent.com/9192912/166171158-80d58118-832d-441f-8764-bc44e6857b8f.png)

**Comment by mark-prins** [comment]
@DhanyaHerath @Chris-Petty would either of you have time to investigate this one? appears to be an mSupply issue and not something that I can resolve in the f/e codebase.

**Comment by bijaySussol** [comment]
@mark-prins : I will retest again

**Comment by Chris-Petty** [comment]
@bijaySussol How'd it go? If I didn't know better I'd guess that the mSupply UI is adding the the lines to the listbox twice? Given that it's not in the database as Mark showed.

**Comment by mark-prins** [comment]
Changing status to `Validated` is key here - so possibly something in remote server then.
Have been testing, and the duplication only arrives when changing status, the stock lines are duplicated at that point.

**Comment by mark-prins** [comment]
My investigation concludes that it's an issue in `remote-server`. I've raised https://github.com/openmsupply/remote-server/issues/1066 to address this

**Comment by bijaySussol** [comment]
> @bijaySussol How'd it go? If I didn't know better I'd guess that the mSupply UI is adding the the lines to the listbox twice? Given that it's not in the database as Mark showed.

@Chris-Petty @mark-prins : 

I had a look at this yesterday but it is always less but i gathered it is not an issue with Sync or neither the Central server because I debug the code to see what or how many sync record once inbound shipment is created through the remote server to send to the central server, when it started processing on Central server to make a copy of it own It already had received those duplicated item line records so Central server process as @mark-prins investigation suggested, it had a type of `I and U` where I = Insert and U = Updated, so that conclude that, It is not sync not Central not the Front end but a communication from remote to central server 

And Type `U` works as insert (I) if there is no records in selection and likewise other wa so probably, There is a clash between the sync Type and the remote server some how created a unique IDs so the check in central server failed to get the selection and it created the duplication? which probably what @mark-prins investigation shows

So, Not a Front end, Not sync, Not central server, It is somehow sending from remote to central asking to create this duplication resulting the ledger issues.
