### ISSUE TITLE
Stock take can be saved without description

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/openmsupply-client#1208]
### Steps to reproduce:

- Setup, remote-server, web-client and central server
- Once setup finished, Login using web client
- Create a new stock take
- Fill in the necessary details
- Don't put any description
- Verify it 
- Stock take created without the description
   - Also wait so that it can make to central server
   - Once reached view that stock take and click OK
      - You will see a alert

It does not matter much to the open mSupply, I guess but this will create an issue on Central server if double click that Stock take click OK always will give an alert

**Comment by mark-prins** [comment]
I've always thought it odd that the description is required in mSupply - and the default of `[date] Stocktake` doesn't provide useful information - we know it is a stocktake, and there is a field for the created date.

Have put in a PR to add a default - hopefully that's the sort of thing you're after?
