### ISSUE TITLE
Outbound: Add Item

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#121]
- Add the ability to add a row to an outbound

![image](https://user-images.githubusercontent.com/35858975/132264525-fc899011-1fbc-4c00-a432-093c29e6c0c3.png)

- Using the `Add Item` button?
- Did this idea get scapped?
![image](https://user-images.githubusercontent.com/35858975/132264547-6f3a2b93-289d-4aa2-8a94-6e4abd2e22c9.png)

**Comment by joshxg** [comment]
Bit more complicated than just 'add an item!!'

![image](https://user-images.githubusercontent.com/35858975/132265424-de98433d-6b86-4967-a0ab-b5e12ac42e81.png)
![image](https://user-images.githubusercontent.com/35858975/132265428-d5f7cd4e-b4ee-4656-80d9-b3ab967a445c.png)

**Comment by richardmoizeau** [comment]
@joshxg, not sure if you need further explanations or clarifications. Let me know :-)
