### ISSUE TITLE
Problem with language detection in Firefox

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/openmsupply-client#1232]
Seems to be affecting Firefox browser only currently (confirmed okay in Chrome and Safari).

After removing all local storage and cookies, Firefox gives the following error when reloading:
![Screen Shot 2022-05-10 at 4 06 26 PM](https://user-images.githubusercontent.com/5456533/167540727-ae4cda18-ba3f-4370-8f6b-e247694ff83b.png)

Probably the locale string retrieved from the browser is fishy -- need to investigate, and maybe provide a fallback if there's a problem?

**Comment by CarlosNZ** [comment]
Weird, this is working fine for me now, even after clearing localStorage. 🤷‍♂️

Will keep an eye on it for a day or two, then I'll close this.

**Comment by mark-prins** [comment]
I'm able to replicate it. To resolve, I've removed `i18next-browser-languagedetector` which returns the browser string, which for me is `en-US`.

We were using the browser language detector rather than just taking the browser string to avoid this sort of problem 🙄

**Comment by mark-prins** [comment]
have put in a suggestion.. for something that fixes it for me
