### ISSUE TITLE
Outbound Shipment: Add item text on body does not work

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/openmsupply-client#1244]
### Steps to reproduce

- Setup remote server, frontend with the central server
-  Make sure the connection is OK
- Login from frontend
- Click on `Outbound Shipment` from the sidebar
- Click `New Shipment` choose the Customer take to the input details of Outbound
- On the body section of page there is a text saying `Add item`
- click on that
- You will see its restricted

**Comment by mark-prins** [comment]
oh, oops. I created a new issue: #1249 sorry. Didn't read this in time! you were quicker than I was at spotting it. 
Should be fixed with #1250
