### ISSUE TITLE
Outbound shipment: useListData hook

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#146]
- A hook `useListData`
- Handles what we need for `ListView` style pages - some actions and getting the 'list data'
- Because some actions will have loading states and error states as well as the query itself, and we can consolidate all that nicely in one hook also list views will all be using sorting/pagination which we can also encapsulate/shove in a single hook nicely/in a way where we can forget about it.
- Also a lot of the actions will be similar on all pages - i.e. `delete`. 

Unsure about:
- Actions which don't require server interaction: export to csv (I'm guessing we'll do this client side, but as an example) even though it is something that might be on a lot of pages.
- Means this is like `useListDataAndTalkToTheServerForMe` hook so there might be a better name

**Comment by mark-prins** [comment]
great idea. 😄 
A suggestion, if we do need to have a local data version too: `useFetchListData` and `useListData`
