### ISSUE TITLE
Framework: Status

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#150]
Unsure which was style was chosen:

![image](https://user-images.githubusercontent.com/35858975/132935837-c57a3f78-a6e3-47c2-8ea7-cbf05021382b.png)

![image](https://user-images.githubusercontent.com/35858975/132935843-99809341-a82b-43a5-98b6-678fd0c278ff.png)
![image](https://user-images.githubusercontent.com/35858975/132935853-98d57a1d-0b91-4cce-b697-7c1892b34a32.png)

**Comment by mark-prins** [comment]
We didn't reach a decision! what I remember is that we don't need all of that showing all of the time. 
I remember not liking the onPress to show more details ( how is a user supposed to figure that out? ) and we didn't like it in the header or footer ( too much other stuff: there are status values there when looking at the detail view of an invoice, for example )

**Comment by joshxg** [comment]
Ah choice. I agree that there is likely no room at the footer or header. I wondered if the status was a hover or press although I don't think that quite addresses your concern with that either.

Back burner!

**Comment by mark-prins** [comment]
Update from Richard, whose memory is better than mine:

- we could have this in the footers but we only need 1. Store and 2. User information
- Sync status will be fine with the Sync button
- regarding the datafile, the idea was to have another option for the user to “copy” technical information (on support’s request for instance) such as : mSupply version number / Datafile / etc...
