### ISSUE TITLE
Condensed appbar buttons for small viewports

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#154]
Catchy title!

I realised that we haven't implemented the condensed buttons as per this design:
![Screen Shot 2021-09-13 at 5 26 24 PM](https://user-images.githubusercontent.com/9192912/133028559-1c44bf5c-bda1-41b0-b136-3f1732aa2a7f.png)

**Comment by joshxg** [comment]
Should this be tied to the drawer being open or only the screen size? I.e. on a big screen if I collapse the drawer, should the buttons be little ones (and maybe we should just disable the drawer expanding on a smaller screen?)

**Comment by mark-prins** [comment]
I think just have it based on screen size. collapsing the drawer gives you more space in the body of the page - reducing the appbar buttons doesn't help with that, and isn't directly tied to the drawer.

and if you want to open the drawer on a small screen, then that is your own problem. I don't think we should disable
