### ISSUE TITLE
Outbound: Comment

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#158]
Another nice little table challenge: adding the comment column. We don't have designs which include both the colour and the comment. The colour was done earlier, and the comment later - the combo appears to have been missed.

If a row has a comment - a mouse over (press on mobile?) to show the comment and a different treatment on the icon to show there is a value

<img width="705" alt="Screen Shot 2021-09-14 at 9 40 22 AM" src="https://user-images.githubusercontent.com/9192912/133160265-196e8998-b764-43b3-bbcb-3fe8e21c3546.png">

and the idea of clicking an empty speech box icon to add a new comment. not sure why some rows have no comment icon in this case

![Screen Shot 2021-09-14 at 9 40 56 AM](https://user-images.githubusercontent.com/9192912/133161036-ccaacc11-1fe3-42ae-82ed-64980268f42e.png)

**Comment by joshxg** [comment]
Oh cool. Wonder if the color column would be better just as it's own, small column like this with no header. Probably.

Maybe: 
- Desktop: Hover and click to open the edit dialog
- Mobile: Click to open the edit dialog (Which is read only when finalised)

**Comment by joshxg** [comment]
Also wondering if just have two small columns one for the color and one for the comment would be OK - probably need to check it out to know!

**Comment by mark-prins** [comment]
Yes, I wondered if two small headerless columns would work. I think so.
Wondering about trying it to see how it would work: the item was missed from the design chat this morning, so likely won't get any design direction for a couple of weeks.

**Comment by richardmoizeau** [comment]
email sent to Manu to (try to) finalise the shipment UI and I did request a preview where color picker and comment icon but no response from Manu (family issues). Would you be happy to give it a go ?

**Comment by mark-prins** [comment]
Possibly we need to bring the comment column back after Craig's comments this morning?

**Comment by richardmoizeau** [comment]
Yes, Shipment-level comment should be in a column as per Craig's instructions. I believe we have a consistent way to deal with comments so I would also recommend to have the Shipment Line level comment in a column too.

**Comment by joshxg** [comment]
I think the comment on a line at the detail level will ensure there is horizontal scroll on the detail views with more columns like a customer requisition, which I would think will make tabbing to the next cell and general usage annoying.

Maybe worth checking if users are really using line level comments to know if we should clutter the ui with this?
