### ISSUE TITLE
Outbound: Optimistic mutation hook

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#189]
- Create a reusable optimistic mutation hook to be used in `useListData` and likely the detail variant

Links: 
- https://github.com/tannerlinsley/react-query/discussions/1084
- https://github.com/openmsupply/msupply-dashboard-app/blob/master/frontend/src/hooks/useOptimisticMutation.ts
- https://react-query.tanstack.com/guides/mutations
- https://react-query.tanstack.com/examples/optimistic-updates-typescript

It's not trivial to make this into a generic enough hook. Mainly the typings get nutty!

**Comment by mark-prins** [comment]
yup. and uh-huh
generic is the dream, and the typings will be wild.
