### ISSUE TITLE
Outbound: Editable cells

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#192]
- Need to introduce an editable cell into the outbound detail page for the quantity!

**Comment by mark-prins** [comment]
Along with the validation - to prevent issuing more stock than there is on hand for a particular batch, and how to handle display of warnings and validation errors?
I like the inline editing, would be nice to have editable cells if we can

**Comment by richardmoizeau** [comment]
Here are all designs for "Add Item" function. We have chosen that there will be no in-line editing even for quantity. However we haven't decided on a way to edit an already created shipment line. You double-click the line and the Add Item window opens ?

https://app.zeplin.io/project/60e44fff6fa942168092f1ff/dashboard?tag=Add%20Item
