### ISSUE TITLE
Outbound: Shift columns from ListView

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#194]
- ListView has a bunch of columns in the middle of it!
- We need to decide where to put column definitions.
- Thinking- column definitions into `layout/table/columns` and then each component with a table has a `columns` file.
- Doesn't help with the 'customisation' problem - a'la mobile reasons, prices and vaccines oh my.
- Maybe need to use a builder pattern to construct a columns array which can specify a column
- Also need to be able to pass parameters to the column - for example the color column needed to have the `onUpdate` passed in

**Comment by mark-prins** [comment]
Thanks, yes - time to tidy this up.
I think a builder pattern would be best, as the column set isn't static - have the column definitions defined and then the grouping of the columns and decoration with event handlers to be managed by a builder. I could see that working.
