### ISSUE TITLE
Warning messages in detail view

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#198]
Would be nice to have these

- `Record not found` if some muppet puts an invalid `id` into the url. Also, should it be more specific? 🤔  _Outbound shipment_ not found? _Invoice_ not found? The first sounds daft and the second problematic if we talk about 'outbound shipment'
- `No items` or similar if there are no things to show in the list

Should add a `no things in the list` for the transaction list also

**Comment by joshxg** [comment]
related: #190

**Comment by mark-prins** [comment]
closing as dupe
