### ISSUE TITLE
Framework: Order of AppBar buttons

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#218]
I think we need to have a way to order the buttons in the AppBar, beyond what we can do currently.

The `Add item` button needs to be on the left, as that is an important / often used button. The `More` has to be on the right, so that it is linked with the detail panel. Currently both of those are added by the page and therefore can't be located at both ends, the buttons which are shown on every page (Docs & Language) are shown on the left.

Wondering about just adding an order property - or an alignment prop, similar to flex: end, center & start; or left, middle & right. 

The comment has been made that Docs isn't required in the top bar, with the argument being that it is only helpful for new users. I disagree, thinking that a 'help' option has to always be readily available, so would argue to keep it on every page.

Might also be time to move `Language` out - that can possibly be added to the settings section for now?

**Comment by joshxg** [comment]
Ah thanks I've been forgetting about this!

I think a prop might work well - I think this would allow us to order the children of the portal.

For example, in the `AppBarContentPortal`, we're able to inspect the children of the portal with `props.children`, which is rendered under the `Box`. If we do the same with the `AppBarButtons`, we could use something like:

```
React.Children.toArray(children).sort(((a,b) => a.props.order - b.props.order ...)
```
