### ISSUE TITLE
Framework: left nav for second level items

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#219]
Clarified with Manu the intention for second level menu items - turns out that I had that incorrect.
What he was intending was:
If the drawer is collapsed, hovering over a top level menu item which has lower level items under it would expand the drawer, showing the lower levels.

The complication is that the drawer would have to remain open only while that menu set is being interacted with and collapse again when a top level item (with no children) is hovered over.

Starting with:
<img width="343" alt="Screen Shot 2021-10-04 at 9 24 09 AM" src="https://user-images.githubusercontent.com/9192912/135770359-92914e74-6546-469e-9a3e-41ab99f1cfe1.png">

Hover over `Customers`:
<img width="318" alt="Screen Shot 2021-10-04 at 9 24 22 AM" src="https://user-images.githubusercontent.com/9192912/135770390-cbe3cecb-b961-4949-87bc-44e58a4a7342.png">
 
The move the mouse and hover over `Invoices`
<img width="287" alt="Screen Shot 2021-10-04 at 9 24 34 AM" src="https://user-images.githubusercontent.com/9192912/135770405-0f2cf9c6-2461-44e5-a3c0-9bc216d5abba.png">

Then move down and hover over `Suppliers`
<img width="148" alt="Screen Shot 2021-10-04 at 9 24 49 AM" src="https://user-images.githubusercontent.com/9192912/135770413-b06504af-a968-4e7d-bf5f-669e845514c4.png">

**Comment by joshxg** [comment]
Hover won't work so well on a tablet, which is one the big reasons for the collapse, I think? Although I do appreciate the ease of navigating to the sub menu items, it doesn't really help the users who have not intentionally collapsed the menu

**Comment by mark-prins** [comment]
yeah, the suggestion was a press event for mobile, which is required with the current version. you have to click to view the customers page and that gives you the lower level links.
