### ISSUE TITLE
Outbound: Exporting to CSV

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#251]
The export to CSV button on the list view

- Is this going to be done client side?
- For this, we would need to query the server for the entire invoice. We might be better off just sending a query for a csv string/blob, in this case.
- Are we then going to turn the csv into a blob client side to download? Since we're talking to the server, it might be easier to return a url to the csv rather than a csv string to then convert into a blob client side to download.

- If we do it all client side:
    - Need a handler to get the invoice
    - Package to convert to csv? I don't want to write a parser - edge cases already taken care of 🤷 
    - hooks to take object into csv and csv into downloadable?

**Comment by mark-prins** [comment]
> we would need to query the server for the entire invoice

Depends on what is in the export though - I was expecting a list of invoices and the data in the list would just be the same as the table, in which case we have one page of the right data client-side.

Sounds to me that server-side would be sensible. I'm not aware of anything that would require it to be done client side
