### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#29]
Before getting to far would be good to add in some localisation.

Think the requirements are
- Able to localise 🙃 
- Can allow specific deployments to augment the localisations. I.e A specific customer would prefer the english string for `item` be `product` [there are a lot of conditionals in current mSupply for this purpose].
- Limit the amount of strings needing to be downloaded. Current mSupply localisations files are 2.3Mb. We don't want a user to have to download all of this in one go and bloat the bundle size- so localisations should be package specific
- We want to be able to *share* strings as much as possible between packages to limit the amount of translations required.

**Comment by joshxg** [comment]
This is actually hard!

Some ideas

### Per package localisations - each package has their own localisation files
- *con*: This would lead to a lot of duplicated strings
- *pros*: Probably the fastest for overall page load speeds
- Could implement something in the build pipeline where we actually reference some central repository of translations and what is actually bundled is the strings..?

### Centralised localisation package. Each package can depends on the localisation package and imports specific files
- *con:* Files would need to be pretty tiny to be worthwhile. If you need just one or two strings from 3 different 100Kb files, this would be relatively useless
- *pro:* Would share a lot of the localisation file dependencies between packages which would reduce overall downloads

### REST server for localisations - One page load send an http request for the strings you need..
- *con*: it's not good
- *pro*: None?

**Comment by CarlosNZ** [comment]
https://formatjs.io/ Too much?

**Comment by joshxg** [comment]
oooo thanks @CarlosNZ - that looks awesome.

It seems that package is able to create translation files from extracting the messages from your JS? That's super cool. 

What I would love would be a way to lazily load a subset of translated strings during runtime - I don't want to load any strings used within requisition pages that are not used in the invoice pages, as an example. But I also want those strings which are used in both places shared so they are only translated once, and only download once.

This example is doing the code splitting which is great: https://github.com/formatjs/formatjs/blob/main/packages/react-intl/examples/StaticTypeSafetyAndCodeSplitting/StaticTypeSafetyAndCodeSplitting.tsx

**Comment by CarlosNZ** [comment]
Yeah, it does look pretty powerful. I did worry that the boilerplate required for every string might be a bit of a headache, but haven't really used it in practice.

But having built-in logic to handle correct pluralisation per language, and number formatting, all in one package seems pretty cool.
