### ISSUE TITLE
OS Detail: stock line allocation

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#291]
Some additional parts to complete:

- Some messaging:
  - the text `## allocated` beside the quantity input
  - make the expiry date red if..?
  - make the placeholder row text red
  - add available quantity to the far right of the autocomplete row? is that possible?
  - show `## allocated` in red if different from the quantity value
- Take account of pack size when allocating; will need to round up to nearest pack size
- Do something with the info icon 🤷‍♂️

**Comment by joshxg** [comment]
I also had a thought about the item selection which could be super annoying or helpful and nice. Unsure.

Could do something like adding `open` to the `Autocomplete` and `autoFocus` to the input and then have the input use something like an `onBlur={e =>  if (!item) e.target.focus()}` so then the list is just open and focus is only on the input or you cancel
