### ISSUE TITLE
Remove editable quantity column from table

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#298]
Doesn't seem like people want the editable quantity cell. I had just completely assumed it would be editable - oops!

**Comment by mark-prins** [comment]
I haven't been told directly that it shouldn't be editable, though I've also picked up on that vibe. I wondered how much of that was sticking to what desktop does?
The initial designs for requisitions came in this morning and they have editable table cells - just like in desktop

**Comment by joshxg** [comment]
NO!
