### ISSUE TITLE
Detail panel: Add pricing section

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#302]
- Need to add a pricing section to the detail panel with totals etc

also:
```
RM: should include
- possibility to add "Other Charges"
- Subtotal, % tax & Total
```

**Comment by joshxg** [comment]
semi blocked as I'm not sure what to do about tax - maybe it's just already on the invoice? Is it editable? Also heard something about tax being on invoice lines instead

**Comment by mark-prins** [comment]
in desktop, there is `tax` on the `transact` level and not on invoice lines - though it sounds like that is coming for the OMSAPI. I was thinking just to have what is currently on invoices in desktop:

- subtotal
- tax percentage
- total

tax is editable ( if preference is enabled ) on desktop

**Comment by mark-prins** [comment]
Mostly done
