### ISSUE TITLE
Add Log tab, remove transport tab

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#305]
The transport tab is pushed to phase2 so we can remove it.

We can add the log tab, though we don't have any designs it should be just a table, I suppose.

Personally I think we should push the log tab out and just remove both tabs

**Comment by joshxg** [comment]
Have no idea how logging is going to be working - unsure if I should just make mock data and say thats how it works or.. 

there's also this one https://github.com/sussol/msupply/discussions/9527

**Comment by mark-prins** [comment]
there is the existing `[log]` which is what the current table is using and we could just bring that across. shouldn't be too hard to query and show in  a table - but is there any actual benefit in having it? I think not.. but what do I know?
