### ISSUE TITLE
List View: group by item

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#311]
Currently all invoice lines are shown. Add the ability to have items grouped by item:

- add a button ( somewhere? perhaps the plus icon? ) to expand all
- and the reverse.. a collapse all when expanded ( the minus icons? )
- If only one batch then batch details appear in the row
- If more than 1 batch, then “[# batches]” appear and you can expand the row - some indication within the row
- Add a keyboard shortcut. Include in KBar

There are no designs, so for now please just wing it and then add to the list of [stuff we made up](https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit?pli=1#gid=1543225647)

**Comment by joshxg** [comment]
Unsure what to do here so will wait for more details or a mock up

**Comment by mark-prins** [comment]
Argh! sorry - I must have missed your earlier comment!
Yes - I thought to do a mock up today of what I understand is the request and see if you think it might work. Agree with your concern about column alignment, so I'm not sure how this is going to work.

And yes.. oops. Group by item. I keep saying 'batch' 🙄

**Comment by mark-prins** [comment]
Ok - here is something:

### Normal view
when the 'group by item' toggle is off

<img width="1366" alt="Screen Shot 2021-11-02 at 4 55 48 PM" src="https://user-images.githubusercontent.com/9192912/139791466-d1c939c3-6aba-4ae9-a8ac-37648c4f449c.png">

### Grouped view
<img width="1367" alt="Screen Shot 2021-11-02 at 6 24 32 PM" src="https://user-images.githubusercontent.com/9192912/139791550-9dff5f8b-6cf4-418c-a515-38e283cebf71.png">

and then expanded when you click on the chevron:
<img width="1367" alt="Screen Shot 2021-11-02 at 6 24 46 PM" src="https://user-images.githubusercontent.com/9192912/139791580-5561d8db-b0fc-4d5f-8860-b5854c887284.png">

which looks something like this..
https://user-images.githubusercontent.com/9192912/139791774-00390842-870e-4c9e-93d4-bcbd6bb88c7a.mp4

**Comment by DhanyaHerath** [comment]
+1 to the Group by item button, though will that just do the same thing as the column chevron?

 The expansion chevron itself is nice - though not sure it's clear that it's a separate section,  on my first look I thought the columns were just misaligned, but maybe on the browser the color change is more clear!

**Comment by craigdrown** [comment]
@mark-prins OK can't resist
1. need a col. for line total (price of line) in both views? (maybe not the detail view)
2. can the unit quantity show for summary lines (in the above you're showing pack qty, which maybe shouldn't show)?
3. can the sell price show a meaningful value in the summary row? (line total / unit quantity)
4. should the Unit qty and Pack qty cols be swapped, or maybe pack qty goes to the left of pack size? (to sort of get a more normal reading of a line: this x that = total)

**Comment by joshxg** [comment]
should list batches and do this much later
