### ISSUE TITLE
Detail View: bulk actions - allocate placeholders

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#314]
Add the bulk actions to the detail view. Should have the following options in it:
- Delete
- Auto Allocate Stock

though, sorry, I don't have detail for what the auto allocation will actually do. This is the new home for the 'grinder' which allocates stock to placeholder lines.. so that. But for selected lines only rather than all, as currently is the case.

**Comment by joshxg** [comment]
Thinking about this more..

At the moment we're querying for all items and all their batches and have that query sitting around to utilise. However I am not sure in practise this will be possible - I imagine stores might have a ton of item lines. 

If this is right, then we either need to have some sort of query for all the items lines for each placeholder item/line, which we can then FEFO assign.

I wonder if this actually might be better as a mutation .. 'assign placeholder lines'

**Comment by mark-prins** [comment]
+1 for a mutation. This feels like a task which requires business logic and therefore should live in the API

**Comment by joshxg** [comment]
Cool.

We will need to save before this, so the backend has all the data. So we'll need at least a couple of mutations, I suppose.

- Blocking spinner
- Send request to save
- Send request for mutation `assignPlaceholders`

?

**Comment by joshxg** [comment]
hmm maybe the blocking isn't needed 🤔

**Comment by joshxg** [comment]
b/e tracking: https://github.com/openmsupply/openmsupply-client/issues/385
