### ISSUE TITLE
Add filtering to `useListData`

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#327]
The backend API is supporting a `filter` object which we haven't been doing at all.

- Implement some sort of filtering mechanism to `useListData`
- Add filtering to the outbound shipments list view & customers

**Comment by joshxg** [comment]
@mark-prins 

ref: https://dev.msupply.foundation/docs/api/patterns/#filtering
ref: https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/blob/master/docs/operators.md [What we agreed to use as filtering syntax]

Have been looking at implementing this and have found it quite difficult. Would like to get your feedback before I make a change request. Specifically, the api is not using a specific filtering type (i.e. allowing equalTo/like v greaterThan and lessThan) per data type, but each field.

The type for an invoice:

```
input InvoiceFilterInput {
  nameId: EqualFilterStringInput
  storeId: EqualFilterStringInput
  type: EqualFilterInvoiceTypeInput
  status: EqualFilterInvoiceStatusInput
  comment: SimpleStringFilterInput
  theirReference: EqualFilterStringInput
  entryDatetime: DatetimeFilterInput
  confirmDatetime: DatetimeFilterInput
  finalisedDatetime: DatetimeFilterInput
}
``

This makes it difficult to type even somewhat generic filtering  - we can't specify allowed conditions on a specific data type (which we could derive) we must specify allowed filters for specific fields which seems to me, to be exhausting.

For example, I would expect to be able to specify a condition for all string types as `equalTo` and `like` (for example) - however some fields only specify `equalTo` (their reference) and some specify both.

**Comment by mark-prins** [comment]
the schema is so prescriptive! 
I really don't want to be holding a map of fields and allowable filters. As a consumer of the API - I would expect that a certain data type could support a certain filter, so I think that's a reasonable ask.
not sure how else to handle the support of custom data types or type inspection??
