### ISSUE TITLE
Outbound status should be automatically set to allocated

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#340]
Currently an outbound is set to draft initially.

We should force the status change to allocated? (maybe when saved with lines?) to mimic the current mSupply behaviour where any stock assigned to a CI is reserved

**Comment by joshxg** [comment]
@mark-prins I suppose we need to wait for a conclusion to statuses for this?

**Comment by mark-prins** [comment]
I was thinking yes, we should - to the original part of the issue. Based on the status discussions we've had.
We _might_ be in agreement with the status as in [this summary](https://docs.google.com/spreadsheets/d/1g80DGamNQ1NoXjMfdMj84YpvRxgsG7tzUkX596CKrvA/edit#gid=0) which is

- Draft : just what you show the user until a line is saved- then it changes to allocated
- Allocated : at which point available stock is adjusted
- Picked : total adjusted - "If you do a stocktake now, you won't count this stock" ( I have no idea what this comment means )
- Shipped : locked for editing - can't change other party or any invoice lines - there is no practical reason to stop other fields being edited, especially if our logging of edits is better

**Comment by joshxg** [comment]
Because we have two save buttons - one being save & confirm allocated (when in draft) and the other being `save` - from what I understand, both will change the status to confirm allocated once a line has been added to the invoice?

do we need to change the button label or give any feedback to the user?

**Comment by mark-prins** [comment]
oh! good catch. 
yes - we should.
a suggestion: we disable `Save` and only enable `Save & confirm allocated` - though the problem is that there's no reason given why the button isn't enabled. 
Otherwise - prompt the user, though it does mean another click to get rid of the warning

**Comment by joshxg** [comment]
I think adding a tooltip on hover of the disabled button (or click on a tablet?) which says "You must set the status to allocated to save this invoice" isn't too bad. Alternatively.. a snackbar/toast on press?

Though I also remember seeing this in https://github.com/openmsupply/remote-server/issues/530

![image](https://user-images.githubusercontent.com/35858975/144541090-a352271a-2d0c-418c-92d2-0eefd0be3822.png)

Which makes me very confused.. but might mean that this doesn't need to be done. And what we actually need to be doing is disallowing `save & allocate` if there are any placeholder lines? Also adding a button to `create invoice with placeholders from this invoice`
