### ISSUE TITLE
Organise types 

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#356]
Our types, specifically the 'domain' ones, are somewhat unstructured and messy

Some are in common and some are in `invoices` etc.

1. Start using graphql code gen to generate types
2. Put them in common. I think they would likely be better in specific places - i.e. the outbound shipment types with outbound shipment, however it seems easier to just codegen to the same place, for now.
3. Don't add codegen to the development workflow. I think it's better, but when the API is more stable and where we don't need to add changes ourselves, as much. i.e. `hold`

I also personally get annoyed with the shapes of the returned objects, in that I have to access things like `invoice.lines.nodes`. Personally, I wonder if it would be better to map each response into a new shape without the `nodes` 🤷 .. though, this can be another issue..

**Comment by mark-prins** [comment]
just to chip in - would love to map the returned object to a better shape!!
