### ISSUE TITLE
Pagination row not forced to the bottom

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#360]
I swear I had this working, but apparently not

![image](https://user-images.githubusercontent.com/35858975/139951003-ed38af2d-1d9a-45a0-b139-1caded533389.png)

Looks better when pagination is stuck to the bottom of the page

**Comment by mark-prins** [comment]
I thought it looked fine at the bottom of the table 🤷  Will see how it looks on the bottom of the page though 😃

**Comment by joshxg** [comment]
Was just a regression I must have caused so thought to fix it up, but I'm happy to not do this if it looks fine!

**Comment by mark-prins** [comment]
looks ok to me and it does keep the pagination close to the area that it affects
