### ISSUE TITLE
Initial dashboard

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#362]
I would like to have something in place which is more indicative than the current skeleton for the dashboard, without going overboard or creating a full implementation.

![Screen Shot 2021-11-03 at 11 00 28 AM](https://user-images.githubusercontent.com/9192912/139957868-e4ef0f6d-0330-4fc2-b896-dd07fe74cc5b.png)

Am basing this off [Dashboard V1](https://zpl.io/VOEAlkk) as I _think_ this was the preferred option ( not certain! )

**Inbound Shipments**
- Show number created today
- Show number created this week ( both could potentially be determined using the list query, but that would be terribly inefficient )

**Outbound Shipments**
- Show number to be picked ( i.e. status === `ALLOCATED` )
- other ideas? The mockup has 'to be picked: This week' but what does that mean?!

**Stock**
- Quantity expired ( quantity? packs? value? )
- Expiring soon ( what is soon? same questions about the unit to use.. quantity, packs, value )

Note: these can be taken inefficiently from the existing API and we'll probably have to do that before the API provides useful information

Unsure what to include under `More Actions` - at this stage perhaps just a link to the list view
I don't believe that we can include any of the 'wizard' buttons right now.. these will require some analysis and then API work

**Comment by joshxg** [comment]
I wonder if it would be better to just make the queries we want for this type of thing in the mock server, then we can just say 'implement this'

**Comment by mark-prins** [comment]
Sounds good to me - I've done the UI, will make some queries
