### ISSUE TITLE
Organise GQL query errors

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#369]
Need to handle the returned errors from gql queries a little more.. elegantly!

This is for:

- outbound list
- outbound detail
- items
- customers

**Comment by joshxg** [comment]
Our mocks aren't returning the correct errors, so would need the backend api and it's a little bit out of sync at the moemnt, so will put this one off

**Comment by joshxg** [comment]
blocked as we can't fully integrate the api right now

**Comment by mark-prins** [comment]
Have made some changes #1131
