### ISSUE TITLE
Add transport details section

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#386]
Add

- Shipping Method: drop down (Air, Truck, Sea, Drone)
- Transport Reference: free text. eg. Air way bill number, tracking number

Tasks
- Need a query for shipping methods. Unsure where these will be stored. I would think `options` would be a good home. This matters because the query could be for `options` with a filter or something else - or, is this just hard coded..?

**Comment by joshxg** [comment]
Blocked as I'm not sure what to do about the shipping methods

**Comment by joshxg** [comment]
Track b/e required changes: https://github.com/openmsupply/remote-server/issues/785

**Comment by mark-prins** [comment]
Note: transport reference done in #1092
