### ISSUE TITLE
Should filter any items which are already in the invoice in the item details modal

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#406]
Currently all items are showing in the drop down, not just those which are not in the invoice already, which results in being able to add multiple lines for the same batch

Two options I can think of:
1. Filter out the items which are already in the invoice
2. When selecting an item which is already in the invoice, essentially acts as you having clicked on the row for the item, showing the invoice lines for that item (I can see this could be cool. But also it could just be confusing, so I think 1)

**Comment by mark-prins** [comment]
I wondered if not showing items in the drop down could also be confusing - but the user did click on 'Add item' so it's probably fair enough that items which are already part of the OS aren't available. 

So I vote for option 1 - gets around the immediate problem; even though option 2 is better, it might lead to confusion
