### ISSUE TITLE
Display if a name is on hold before trying to make an invoice

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#451]
mSupply:

![image](https://user-images.githubusercontent.com/35858975/142698358-0f8904ea-799f-449f-b15b-18f5ef6df2cc.png)

should we be displaying if the name is on hold? Additionally if the name is for a stock transfer (red highlight, I think?)

Have added to the api changes if so: https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=1127702983&range=A109

**Comment by mark-prins** [comment]
the row colour would require `type` from the API too, which is also requested in the [API change](https://github.com/openmsupply/remote-server/issues/595)
