### ISSUE TITLE
revert all changes to graphql schema making it incompatible with the current backend

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#454]
- *I* want to work on inbound shipment mutations and also go back to error handling and polishing outbounds.
- *I* want to ensure that that we stay compatible with the backend because:
    - Implementing the error system in the mock server is likely not worth the time.
    - It's taking so long for changes that I think a better system would be to move on to a *new* area rather than cause incompatibilities. For example, move onto other areas where there are not already GQL types defined which cause the incompatibilities - defining the requisition types or implementing a 'log' type.
    - This is in contradiction to wanting to work depth rather than breadth, but that is, I think evidently, not working well.
    - We can have the service worker capture any requests which aren't implemented on the backend - i.e. for requisitions or updating requisitions, but we can't 'change' queries that are incompatible with the backend - or, at least, it would be more difficult. Ideally for me, we still have the exisiting ones implemented so that we can use the service worker for tests and for when we are developing normally so we don't have to run the rust server *all* the time, just when implementing new features.
- And on the front-end-fun branch: It requires other changes, I think? It's not working for me - I think it requires schema changes and I think it'll take less time, though a bit messier, to just revert all the incompatible changes.

To do this, I want to:
- Comment out all the changes in the schema which is incompatible with the backend
- Comment out all the changes in the gql operations which is incompatible with the backend
- Comment out all the changes in the code base using the fields/types which get removed from the schema is incompatible with the backend

Not ideal but I've checked and there aren't really many changes - mainly sorting, colour, statuses/dates and some fields on the lines. Commenting out so they can be re-added, eventually.

An issue right now is that graphiql, where I've been getting a pretty print of the gql schema, doesn't work on the current remote server develop branch. It appears to be from the changes made recently to using workspaces, but I have no idea. I've found a commit which has graphiql working from which I don't *think* there are any other schema changes since. So, I've made a branch from that older commit https://github.com/openmsupply/remote-server/tree/%23check-graphiql which has the same schema as we do currently. Other changes are in PRs but I don't want to bother spending time on that.. as even with those changes, we still won't be compatible.

This could be a really bad idea. Hope not.

**Comment by mark-prins** [comment]
I agree - not ideal, but something needs to be done. I don't want to maintain a separate API branch and since we can't have queries asking for fields that aren't there, I think we have to try new areas rather than depth within the areas done.

An alternative is to move away from the API entirely and use only mocks but I'd rather not do that. Better to have the front and back integrated and any gaps visible in order to fully test the integration and bring some pressure to getting the work completed.

**Comment by joshxg** [comment]
Yup. I think we could potentially move to a more mock heavy approach once we have integrated and have a pattern for error handling in place, maybe!
