### ISSUE TITLE
Arabic/rtl style updates

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#465]
:( !

![image](https://user-images.githubusercontent.com/35858975/142784516-8fac6195-b3bc-4007-879e-24499c2d7d3c.png)

This is similar to how the stepper looked in the storybook. Though it seems fixed there!

**Comment by mark-prins** [comment]
The status stepper is now looking ok:

<img width="335" alt="Screen Shot 2021-12-24 at 9 38 36 AM" src="https://user-images.githubusercontent.com/9192912/147290636-280dcd63-7821-4122-b6f2-631ce7a527f5.png">

though I've found a few other things that need tidying up
- [ ] Dashboard: spacing in StatusPanel
- [ ] SidePanel: spacing around `Actions` and the action button + icons
- [ ] IconWithButton: spacing between text and icon
- [ ] Breadcrumb: spacing between text and icon
