### ISSUE TITLE
SummaryItems have a `lines` key as well as an `items` key which is confusing

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#470]
Current `OutboundShipment` type extends `Invoice`. `Invoice` has `lines` which is an array of `InvoiceLines` and `OutboundShipment` has `items` which is an array of `OutboundShipmentItem`s.

`OutboundShipmentItem`s contain `InvoiceLines` - so the `InvoiceLines` against the `Lines` key become out dated. 

Replace `lines` with the `OutboundShipmentItem` array?

**Comment by mark-prins** [comment]
Sounds good, thanks!
