### ISSUE TITLE
Warn the user when navigating a way from an invoice that hasn't been saved

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#498]
When navigating away from an invoice which needs to be saved, stop the user and warn them.

- Will require managing some sort of state for knowing when the invoice needs to be saved

**Comment by joshxg** [comment]
So need to know if any line has been updated or the invoice itself.

Right now we track if the lines have been created, deleted or updated. The invoice itself isn't being tracked right now but shouldn't be too difficult.

The problem: 1) flagged as updated 2) send for update 3) edit straight away

- If you remove the needs updating flag after 2, if 2 fails, you need to rollback - so you also need to track when the request is in flight
- If you wait for a response from 2 to clear the flag (essentially a fourth step) then you might not send the update that has just happened

I think rolling back should be fine?

**Comment by mark-prins** [comment]
Or you make things a little laggy for users..
2.5) prevent edits while you wait for a response from the update
2.7) clear the flag
3)    edit 

Given that the failure is unlikely, the rollback would be the least painful for users.

On another note.. thanks! we talked about a warning on cancel / navigating away in the ui meeting a couple of days ago and I haven't created an issue for it yet. One step ahead, as usual.

Was thinking of [onBeforeUnload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) maybe with a nice looking version with [routerWillLeave](https://github.com/remix-run/react-router/blob/v3/docs/guides/ConfirmingNavigation.md) though that would make two versions and onbeforeunload can't be styled.. so maybe just that?
