### ISSUE TITLE
Data table keyboard navigation

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#500]
Bit of a random idea..?

I thought it would be very useful to have at least up and down working for rows of the data table

I also thought having a consistent keybinding of something like.. "cmd+f" to focus the first cell in the data table on a page would be really cool

**Comment by mark-prins** [comment]
Not that random! I have been wondering about keyboard shortcut support - and tables are so central to the whole thing, we really need some way of getting around them. navigating up and down rows, with enter for the onClick action would be super   if we could. First cell focus would be helpful - maybe we also need to have a way to focus back to other input elements too? swap between table and other bits?

**Comment by joshxg** [comment]
Ah yes. Good incentive to keep pages consistent is that we can have nice and easy keybindings to 'target' an area.. i.e. d for the data table, p for the side panel and b for the button area or something like that. Surely that's super easy, right? 😁

**Comment by CarlosNZ** [comment]
Do we want a generic `useKeyboardShortcuts` hook? 

You initialise the hook with an array of key definitions mapped to callbacks (and maybe some options defining focus areas or something), and the hook contains the event listeners / keyboard state and runs the callbacks accordingly.

I seem to remember seeing some discussion of this on here somewhere already, but can't find it now.

**Comment by CarlosNZ** [comment]
Suggested key bindings:

In "Breadcrumbs" component
- `Escape` -- goes up one level in url/breadcrumb path

In "DataTable" component
- `Up`/`Down` arrows -- move focus up/down rows in table
- `Enter` -- open detail view of focused line
(I don't think we need `Cmd-F` to focus first line, as it can just start at the first line when you first press `Down` arrow (or start at the bottom if you first press `Up`)
_Eventually (but maybe not for initial prototype):_
- `Page Up`/`Page Down` -- navigate through pages
- `Shift`/`Ctrl-Enter` -- select/check rows/row range as per standard Finder/Explorer selection rules

There's currently no concept of a "focused" row in DataTable, only the "hover" effect for mouseover, so will need to add a `focusedRow` state variable probably (and then the conditional style can follow mouseover OR isFocused)

It looks like this _should_ be do-able just using Kbar's dynamic actions list using the `useRegisterActions` hook, but will need to confirm this.
