### ISSUE TITLE
Add storybook

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#51]
Before creating so many packages, would it be useful to have story book set up?

I know when working in a big code base like Grafana it was incredibly useful.

I know this will take some time to setup. Will take more time if we want to set it up.. later?

@mark-prins think this is useful?

**Comment by mark-prins** [comment]
Yes, I was hoping to add.
We put it into universal codes, and didn't actually make use of it.. but I'm not put off! I think for a project like this it will be really helpful!
