### ISSUE TITLE
Location queries

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#510]
- The current development branch on the backend now has support for querying for locations
- Note: No support for mutations yet
- Would like to setup some queries for locations
- I would really like to setup something similar to `system/item` and `system/names`, where we can export a `useLocations` hook as well as a `LocationSearchInput` or something component. But - locations aren't system data. So, where can we put it?

I wonder if we should put off playing with locations until there are mutations. They won't sync as they're store data, so we will need to manually create the locations in the database which is a bit annoying but not the end of the world(since there also isn't any migration when the database schema changes we need to redo it 🤷 )  . We forgot to explicitly ask to be able to create or update locations, only to read them .. sigh!

**Comment by joshxg** [comment]
I can categorise it under anything meaningful which makes me think 1) shouldn't bother or 2) make a `locations` package. I can't decide which.

Locations are one of the only store data which seem to be as cross cutting as system data. For example items are used in multiple places and so are locations. Sensors are store data, but only really used in cold chain related things. Periods are store data, but only used for requisitions.

Maybe assets are the closest thing? They're under a top level nav header of modules/toolbox which seems OK. Maybe a package `toolbox` 🤷

**Comment by mark-prins** [comment]
I like the idea of `store` for store data, similar to `system`, even though there's only the one thing in it!
Or we could just pop locations into `system`, they are store data which is different to the other stuff.. but they are shared across a bunch of things and therefore similar in that way.

The category of `toolbox` is more about grouping things for the UI and less about grouping reusable data together, so that'd be my least favourite option.

**Comment by joshxg** [comment]
all good points. I'm leaning toward shoving locations into `system` for now as I can't think of anything else that would go into `store`.

Maybe `stock lines` could live in `store`. But `periods`/`indicators` would fit nicely in requisitions, probably. There's a bunch for dispensing, but I imagine a specific `dispensing` package for that - same with vaccine/cold chain stuffs.

Possibles I can think of are `NameTag`, `Preferences`, `User`.. but they're all small and seem like they'd live nicely in `system` also ..

**Comment by joshxg** [comment]
Ah, and I was mistaken about location mutations - looks like they're getting in now
