### ISSUE TITLE
Drop down or autocomplete style cell for adding a location to an inbound location

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#511]
We need a way to select a location for an inbound batch. Think another autocomplete?

**Comment by mark-prins** [comment]
possibly a select would be ok? how many locations to people usually have?

**Comment by joshxg** [comment]
Yeah you're probably right. Though an autocomplete might have a slight advantage as you're tabbing through the cells and are not using the mouse - I suppose it is sort of the best of both worlds in a way?

**Comment by mark-prins** [comment]
heh. just after commenting I saw the issue about locations and thought that since there is a query to fetch them, an autocomplete, which already has async loading in it, would be more the go! and you can search easily if you do have a ton of locations. it is best of both worlds
