### ISSUE TITLE
Service worker handlers cleanup and enable workign in tandem with the backend

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#541]
At the moment the service worker is off in development (I think 🙄 ?)

i.e. uses 

```
if (process.env.NODE_ENV === 'development') {
  const {
    setupMockWorker,
    // eslint-disable-next-line @typescript-eslint/no-var-requires
  } = require('@openmsupply-client/mock-server/src/worker/client');
  const worker = setupMockWorker();

  worker.start();
}
```

- We should change this to instead, have a toggle to disable the worker completely (This gives the option of using the apollo server)
- By default, disable the worker in development for some queries but not others - i.e. querying for requisitions, stocktakes - this is so we can run the backend on the demo site and then have the worker support the pages that are unsupported by the backend.

Tidy up:
- A general tidy up of the `handlers.ts` file - splitting into functional areas similar to how the mock server is set up. Essentially, the `handlers` function just needs to replace the `schema/Invoice.ts` files etc.
- If we can somehow also support using specific handlers in tests that would be amazing - i.e. if I wanted to write a jest test for the `ItemSearchInput`, it would be great if I could provide a list of items in my test to a handler, so the worker intercepts the request within the jest test and I can then test whether those items were rendered, rather than the current implementation where it is a random set of data generated

**Comment by mark-prins** [comment]
thanks! I was going to write up something like this too

**Comment by joshxg** [comment]
@mark-prins 

Hmm, I suppose the `process.env.NODE_ENV` is working on the demo site and preventing this from starting up? Or is there something else on the demo site build?
