### ISSUE TITLE
Add style property to column definition

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#558]
Would like to be able to change the font size of the column headers. I thought a simplish way to do this might be to add a `style` prop to the `ColumnDefinition`.

Maybe something like

```ts
interface ColumnStyles {
    cellStyles: // Same object as `sx`?
    headerStyles: // Same object as `sx`?
}
```

It's also possible that we can just reduce the column header font sizes in general 🤔

**Comment by mark-prins** [comment]
There are other issues for font size realignment: #1149 #517 
Will close this for now, haven't had the need for column style props yet.
