### ISSUE TITLE
Drawer navigation item alignment

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#56]
![image](https://user-images.githubusercontent.com/35858975/129651300-e73b8c10-f832-4c49-b507-4afa8daf341e.png)

V

![image](https://user-images.githubusercontent.com/35858975/129651317-80abbe48-5bf3-45ff-8f3d-63dd9ad68dd6.png)

**Comment by mark-prins** [comment]
Sorry - feeling stupid for asking but this is like a spot the difference and I'm not seeing it.
I've only got the line height on the 2nd level menu items, what else is wrong?

**Comment by joshxg** [comment]
hahahha. Sorry.

The RHS of `Customer Invoices` is closer to the border on our version than on Manus version.... the 'text' is 'centered' in the oval, where as ours looks right aligned or something.. 🤣 

I think it's a 'once you see it'
