### ISSUE TITLE
Add correct customer requisition columns

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#564]
As per: https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=320810900&range=222:222

At the moment the columns on a customer requisition aren't right.

I'm not 100% sure what the columns should be. For an ad hoc customer requisition, the columns might be different to those listed (from my experience with adding ad hoc customer reqs to mobile, we had to add many more columns).

So, would likely need to confirm the exact requirements for customer requisitions and whether ad hoc ones differ

**Comment by mark-prins** [comment]
Note: the additional columns listed in the requirements sheet are

- period
- program

which are out of scope for v1.

**Comment by richardmoizeau** [comment]
Are they out of V1 ? As per our last discussion I think we were supposed to have programmes.

**Comment by mark-prins** [comment]
things keep changing! originally out. I _think_ they are in scope again, but I also think it is very unlikely they'll get finished

**Comment by mark-prins** [comment]
**List view**
- Requisition number
- Other party name
- Date entered (to be added. suggest `createdDatetime`)
- Requisition date (only required when manually created reqs are a thing)
- Status
- Comment

**Detail view**
- item code
- item name
- unit
- our soh
- customer soh ( missing from API )
- customer requested quantity ( `` )
- already issued ( sum quantities from `outboundShipmentLines` perhaps )
- remaining to supply ( missing from API )
- amount to supply ( `supplyQuantity` )
- comment

**Comment by joshxg** [comment]
already issued should be `requested - remaining to supply`

also noticed the STATUS column on the list view was using the raw status rather than a translated string

**Comment by mark-prins** [comment]
🤦  oh yeah. of course

**Comment by andreievg** [comment]
> customer soh ( missing from API - could query items and pass in the other party storeId to the stats node 😆 )

hmm, linked_requisition_line -> item_stats, can expose more direct way
