### ISSUE TITLE
inbound shipment pricing details123

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#572]
Need to add the pricing section to the inbound shipment detail view

https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=320810900&range=A152:C152

**Comment by joshxg** [comment]
@mark-prins 

Thinking service charges something like.. 

![image](https://user-images.githubusercontent.com/35858975/147718495-05b8a770-939c-4342-9550-29efb2e312d7.png)

Push the button to add another? 🤷 

![image](https://user-images.githubusercontent.com/35858975/147718531-69fd15f3-11f5-45e2-9abe-3f7b7b7b6ec1.png)

**Comment by joshxg** [comment]
On second thought.. if I enter values here and optimistically update that's going to be a bit annoying to debounce and keep all the values in sync.

Would be significantly easier to use a 'service charges' modal just the same as the normal invoice lines...

So i'm thinking something more like 

![image](https://user-images.githubusercontent.com/35858975/147722710-cc31c40a-fb4b-4481-a50d-da313de28e3d.png)

Where the `+` button is the same as the add item button but opens up a modal with a list of key:value pairs of service charges

**Comment by joshxg** [comment]
Will use this issue for the pricing details in the side panel for both inbound and outbound

Chat with @richardmoizeau :

Change to something like a hybrid of these two:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/35858975/157562108-85bfc6dc-3791-4f24-81fa-87eea0e87695.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/35858975/157562137-9e28e0ce-6920-4eeb-8391-25d27b077495.png">

-The pencil will allow editing the tax value, changing the tax value for *all* lines in that 'section' (this will require a batch update of all stock lines, for example).
- Also will need to put individual line tax values in the line edit (and list?).

Note: 
- Is 0 a good default for tax?

**Comment by mark-prins** [comment]
The tax default is tricky - safest to go with `0`
