### ISSUE TITLE
When creating - have an indication if the selected supplier is internal or external

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#574]
For supplier requisitions

requirement: https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=0&range=A217

Since the requirement for selecting a customer for an outbound is not clear whether we should indicator transfer stores or on hold customers, I suppose this is unclear also?

**Comment by mark-prins** [comment]
not sure, added to my list of questions. I think yet, we should indicate.

**Comment by joshxg** [comment]
Sweet!
