### ISSUE TITLE
Supplier requisition add/edit item modal

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#575]
'Epic' issue for the supplier requisition add/edit item modal.

Really unsure about the current ui designs to break it down into tasks just yet

**Comment by joshxg** [comment]
Going to look at implementing this by just using the top of this and the bottom and missing out the middle completely

![image](https://user-images.githubusercontent.com/35858975/155244984-de1fff1f-56a3-4cab-8473-309a57cd2fae.png)


Though, I do have a concern that it looks inconsistent with out current modals

![image](https://user-images.githubusercontent.com/35858975/155245034-ac3e9a35-a734-45f3-907f-4ea551da4038.png)

Personally, I feel the consistency is valuable, so would favour implementing a modal similar to what we currently have.

Something more like:

![image](https://user-images.githubusercontent.com/35858975/155245559-8233456c-a86c-4aeb-a47d-70238327fac0.png)

obviously without the massive middle gap between content and buttons.

Or.. I could just do what the designs show. What do you think @mark-prins ?

**Comment by joshxg** [comment]
Ah, there is a somewhat minor complication. In my prototype mockups I hadn't put a suggested/calculated quantity, as that is normally in the chart area. Still not sure if we're doing charts (though, I would tend toward them not being done) so it would be good to still show this value.

This value comes from the requisition line. When we're first selecting an item, we haven't made the requisition line yet, so we don't have access to the value.

This is harder when using the 'consistent modal' approach. However with the original designs, I believe the idea would have been to 'select' and item from a modal similar to the one used when selecting a customer/supplier, in which case we would have created the requisition line before opening the 'edit' modal.

A fix I can see is an endpoint for: usageStats(itemId) - this would return all the chart data, including suggested quantity

**Comment by mark-prins** [comment]
I like the new design and would prefer to implement that, though I don't like the inconsistency that introduces.
The item selection is an issue, as is the lack of requisition line and therefore stats. An `usageStats` endpoint would work - though I also wonder if the `item.stats` would have enough data in it? There's SoH and AMC.. with the min MOS we could show suggested quantity. Perhaps extend the stats with 'stock on order' too?

Would also like to get the charts done if at all possible!
