### ISSUE TITLE
The comment column for supplier requisition lines should be the speech bubble column

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#577]
Currently the comment column for supplier requisition lines is just a standard text cell.

Since there are so many cells, having the smaller speech bubble column would be good.

Should the comment be editable?

**Comment by mark-prins** [comment]
would be good! Should be editable, I think

**Comment by joshxg** [comment]
Since nothing else in the table is editable I'm wondering if I can get away with just utilising the existing non-editable column 😁

**Comment by mark-prins** [comment]
Sold! Can I change my earlier opinion? go with non-editable
