### ISSUE TITLE
Supplier requisition lines: filter by item name

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#578]
Add a filter input for supplier requisition lines: https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=0&range=A234

**Comment by andreievg** [comment]
https://github.com/openmsupply/remote-server/issues/766

**Comment by andreievg** [comment]
@joshxg is this important to be done on b/e or can this be done in f/e ? 

It's not trivial to pass params to loaders, but can be done if needed

**Comment by joshxg** [comment]
I think filtering lines should be done in the frontend

**Comment by mark-prins** [comment]
The filter is the `Filter Items` one on this view in mSupply:

![Screen Shot 2022-03-18 at 8 43 26 AM](https://user-images.githubusercontent.com/9192912/158883238-f73938c1-a913-444a-b710-4b5d19b7e33e.png)

Applies to Internal Orders, which is the current name of supplier requisitions. So just a filter on the detail view screen - without the `x of n items visible`, we don't have that anywhere else so I think we shouldn't do it here.

**Comment by CarlosNZ** [comment]
> I think filtering lines should be done in the frontend

I guess this could be a bit of a problem if there is more than one page of lines. Is that likely?

Cos the b/e will only return one page, and then if you filter it front-end, there could be results that don't show up because they would have been on the next page of results returned. That likely to be an issue?

**Comment by CarlosNZ** [comment]
> > I think filtering lines should be done in the frontend
> 
> I guess this could be a bit of a problem if there is more than one page of lines. Is that likely?
> 
> Cos the b/e will only return one page, and then if you filter it front-end, there could be results that don't show up because they would have been on the next page of results returned. That likely to be an issue?

Never mind -- I see the `requisitionByNumber` query doesn't even have pagination options. So front-end filtering will be fine :)
