### ISSUE TITLE
Change the threshold MOS of a supplier requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#580]
- Change the threshold MOS of a requisition
- https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=0&range=A243
- unsure about the input component for this - guessing a select?
![image](https://user-images.githubusercontent.com/35858975/144513027-2b1e1f19-d50a-4e5e-b203-c7387244453e.png)

**Comment by mark-prins** [comment]
yes, I was thinking an input for a number originally but where I remember us ending up was a pre-defined list of options which the user could select from.

**Comment by andreievg** [comment]
This should be available when requisitions are merged, btw changing threshold or max mos would recalculate all lines in requisition
