### ISSUE TITLE
Add/Edit item functionality for customer requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#590]
Epic for the add/edit item functionality for a customer requisition

Currently you add an item like:

![image](https://user-images.githubusercontent.com/35858975/144530843-e93406bf-a615-4a73-a8ce-08fcb9626c64.png)

- There is no edit modal.
- You can edit the cells in the main list view

Personally I find the inconsistency of which detail view has editable cells and which has modals etc quite confusing so would prefer to just stick with click to edit 🤷

**Comment by mark-prins** [comment]
+1 for click to edit and having the views consistent

**Comment by andreievg** [comment]
I thought, as per our last meeting that manually creating customer (response) requisition are out of scope ?
I think manually addition of lines of response requisition is only allowed when it's manually created

**Comment by joshxg** [comment]
> I thought, as per our last meeting that manually creating customer (response) requisition are out of scope (for v1) ?

1. This is a pretty old issue!
2. I only remember hearing that we weren't doing program requisitions. Maybe I need to listen better...

**Comment by mark-prins** [comment]
I don't even remember discussing requisitions! Programs are out of scope for v1 though 😄  Nothing in my notes, or Craig's summary about requisitions

I'd say manually created response requisitions are in, with a lower priority than automatically created. Where it fits in terms of priority with returns / credits, not sure. I think returns first and then come back to this.

**Comment by andreievg** [comment]
Hmm, i remember pretty clearly that they are out of v1, but yeah, let's see what Craig remember : ) [doc](https://docs.google.com/document/d/1Poe0jo7yb35kEKnDNu-HIdcDH-u7OFuukKOltEBOs_U/edit#heading=h.v7n0ygu435li)

**Comment by mark-prins** [comment]
on the wish list for v1 - the comment was `most likely not required` though ideally yes, v1 with a low priority and only do if we have time.
