### ISSUE TITLE
Add customer requisiton max MOS 

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#591]
From what I can tell this is a field from `[name]default_days_of_stock` which is read only and just for display purposes

**Comment by andreievg** [comment]
Oops this issue is for manually created response requisition. Yep for auto created response requisition we duplicate it from request requisition (should be in once all requisition work is merged)

Sorry i got confused from `[name]default_days_of_stock`, so i though it was for request requisition.
