### ISSUE TITLE
Create a customer invoice from the details and some subset of the lines from the customer requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#592]
As above!

In mSupply, a create customer invoice button which sets the status to confirmed:
![image](https://user-images.githubusercontent.com/35858975/144537131-0ef607cf-ffab-4027-97a1-d2b62116b532.png)

Though, this button seems to create it for all lines, not a sub set. So, not sure what is desired.

- Could do something with the `Save & {next status}` button. But then you either, can't finalise or can't create multiple customer invoices.
- Could do something with the bulk actions drop down - select a bunch of rows, 'create customer invoice from selected rows'?

All the lines in the CI are placeholders from this action also. I am thinking a mutation for `createCustomerInvoiceFromRequisition` with arguments of either the requisition ID, or an array of item lines might be the way to go

**Comment by mark-prins** [comment]
It creates it only for lines that have a positive number in the `Supply this invoice` column - so technically it is possible to create multiple ci's.. but not obvious!

An option to create from selected rows would be much clearer

The UI meetings have also talked about the pointless extra step of creating a placeholder line and then needing to use the meat grinder to magically allocate. We thought it would be easier for users if we just FEFO allocated automatically 🤔

**Comment by joshxg** [comment]
Ah right, yes.

Well creating an invoice with fefo allocated lines is even more reason to use a mutation end point, I think

**Comment by mark-prins** [comment]
Thanks Andrei - that's super helpful!

As above, we had talked about
- being able to create an invoice for a subset of items
- automatically allocating stock to the invoice; creating a placeholder line requires the user to allocate which is an extra step that could possibly be automated

I think the mutation is fine for now - later it would be good to have the option of passing in line ids.. but not now

I have a bonus dumb question:

> any invoices and lines that already have lines (even unallocated) linked to this item

When you say 'item' do you mean 'requisition' or 'item'? Was wondering
- If 'requisition' then how do people create an invoice which partially fulfils the requisition, when `createRequisitionShipment` will create an invoice which contains all rows for the full supply amount?
- If 'item' then is that for the same customer but on any invoice?

**Comment by mark-prins** [comment]
🤔  What about doing this in order to get the issue moving?

- implementing the 'create outbound shipment for all the lines in the response req and make placeholder rows' now
- create a new issue for the 'automatically allocate placeholder lines' part : and do that later, but soonish
- create a new issue for the 'create a shipment from a response req, specifying which rows to use' : and do that later
