### ISSUE TITLE
Requisition statuses

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#594]
Currently using just placeholder statuses for both supplier and customer requisitions.

In this https://docs.google.com/presentation/d/1eEe0uBGvkXbYnKc2oLO2U0qRwFv4l0ws4QwFZa6e74s/edit#slide=id.p slide deck, the statuses are:

*Supplier*
- Draft
- Sent
- In progress
- Finalised

*Customer*
- New
- In progress
- finalised

In this zepplin pic the statuses are:
![image](https://user-images.githubusercontent.com/35858975/144538754-0dbd16cd-b7ad-48b2-93ae-aa19dc7f21d6.png)

- Draft
- Send
- In progress
- Cancelled
- Request for modification
- Finalised

Need to determine what is correct and communicate that with the backend

**Comment by joshxg** [comment]
Hmm. Going to mark this as blocked for now

**Comment by andreievg** [comment]
Once requisitions are merged this should be done. 

We've had a follow up discussion with Richard and Craig before API was implemented for this and the conclusion was updated in: https://docs.google.com/presentation/d/1eEe0uBGvkXbYnKc2oLO2U0qRwFv4l0ws4QwFZa6e74s/edit#slide=id.p

And this issue https://github.com/openmsupply/remote-server/issues/703

![Screen Shot 2022-02-14 at 10 54 12 PM](https://user-images.githubusercontent.com/26194949/153841230-1b11bf4d-a3fc-4cfb-945c-475dd790a2b2.png)

**Comment by joshxg** [comment]
thanks @andreievg !
