### ISSUE TITLE
Update invoice dates123

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#627]
The invoice dates have been updated on the server. i.e. `pickedDatetime`, `allocatedDatetime`. They're used in the `StatusCrumbs` component especially.

We should cast these to `Date` as they come through the wire.

- Add date time fields with a type of `Date` to `OutboundShipment` and `InboundShipment`
- Update the API to parse these to dates
- Update uses in the UI

**Comment by mark-prins** [comment]
@joshxg 🤔  Shall we just close this one? Using dates was giving the re-rendering issue wasn't it?

**Comment by joshxg** [comment]
Yup, thanks

**Comment by joshxg** [comment]
Basically will be best to keep dates as whatever format is returned by the API and then format at the UI end.. ideally that would be the same format coming from the API, but I don't think we will get there. maybe we can bring it up?
