### ISSUE TITLE
Footer status popup

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#628]
Couple of minor things arising from the status changes.

1. The popover is flashy - I have the mouse in the same spot, but the hover cycles between focus and blur
![poppy status](https://user-images.githubusercontent.com/9192912/145488188-63626955-9a0f-44e9-813d-9d8a4d05aa3b.gif)

2. The popup could do with being bigger now that there is more in it
<img width="288" alt="Screen Shot 2021-12-10 at 11 04 51 AM" src="https://user-images.githubusercontent.com/9192912/145488213-5eb7ff24-62c8-4518-bada-157a0be516dc.png">

**Comment by joshxg** [comment]
Ahh! oops 🤮
