### ISSUE TITLE
OS/IS: Update mutation shouldn't set status

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#650]
Inbound & Outbound shipments aren't updating because they are trying to set the status, and only prescribed values are allowed for the status field, so the update fails.

The update mutation now allows partials updates, we can send only modified fields

**Comment by joshxg** [comment]
Oh gosh. That's annoying..

I should have picked up on this earlier.. instead I did dodgy type assertions. Sorry!

I do see the point but .. ugh! 

Tracking changes on the invoice document itself seems like a lot of overhead with no payoff? I suppose there is something with conflicting with others editing the record but it still seems like a lot for very little? I mean, there are ~5 fields on the invoice itself which can be updated.

At the moment the `inbound` is heading toward doing this as we're updating on the fly, so have been using this mutation: https://github.com/openmsupply/openmsupply-client/blob/b5ac19cccbce71e77ca34752860c51b0424cd559/packages/invoices/src/InboundShipment/DetailView/api.ts#L317 so when using `const {comment, update} = useInboundFields('comment')` we just call `update({comment: ""})` - but I suppose this should be using the update shipment input type instead. However adding/editing lines is still just sending the whole invoice, but we can remove that easily enough.

Might be a bit of time before getting to outbound so maybe we can just add something like`if (status !== 'VERIFIED' || status !== 'DELIVERED') delete invoice['status']` .. 🙄 

into https://github.com/openmsupply/openmsupply-client/blob/b5ac19cccbce71e77ca34752860c51b0424cd559/packages/invoices/src/OutboundShipment/DetailView/api.ts#L100-L112
