### ISSUE TITLE
DataTable could do grouping of rows

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#662]
While working on the delete for inbound shipment lines, I wondered if we could do grouping in the `DataTable` component rather than having the summary items..  I.e. adding a prop `groupBy={"someColumnKey"}` and then in the `DataTable` component, we simply do something like 

```
const rows = useMemo(() => {

if (!groupingColumn) return data;

const groupingColumn = find the column to group by

const groups = {}
for each row
const value = column.accessor(row)
if groups[value] groups[value].push(row)
else groups[value] = [row]

return groups flattened to objects like `{ id: column.accessor(row), grouped: array of grouped rows }`

},[data, columns])
```

Then, the type of a row is either the generic `T`, or `{ id: string, rows: T[] }`. So we then add to the column definitions an accessor like:

```
(row) => {
    if ('rows'  in row) // this is a grouped row, so aggregate, show [multiple], show an average, whatever makes sense for the column
   else just the normal behaviour
}
```

**Comment by mark-prins** [comment]
thanks! yes - had a similar thought and hadn't worked it through yet. It's a great idea

**Comment by joshxg** [comment]
Had a bit deeper of a look.

Couple of issues, mainly with typescript:

- Doing this means the type of the "row data" needs to change to `T | GroupedRow<T>` (where GroupedRow is `{ id: string, subRows: T[] }` which is a little annoying when you're not using a grouping mechanism (I think it's mainly in invoices/stocktakes and nothing else?) - It's not too bad, but the `accessor` for example needs to check for `T or `GroupedRow<T>` regardless of using grouping or not
- The `Columns<T>[]` supplied to the table becomes a little annoying in that we are creating an array of columns for a row type of `T`, but when using the columns within the `DataTable`, the row type becomes `GroupedRow<T> | T` - I'm not exactly sure how to fix this 🤔 

Soo.. as much as I would love to do this, my typescript knowledge isn't quite there to get it done without a significant time investment :(

So, I think having the grouping done in the `GeneralTab` is good 😁

**Comment by mark-prins** [comment]
cool - would love to do this too.. but also think maybe just close the issue and think about it later?

**Comment by joshxg** [comment]
Yup
