### ISSUE TITLE
`NameSearchInput` on detail views could look better

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#679]
Just taking a little walk around and being picky.

![image](https://user-images.githubusercontent.com/35858975/146897095-00737228-524f-4687-8362-8e9966d7c5d0.png)

This input here has been annoying me somewhat 🤔 

Some possible things:
- Wider? Though, don't really want the input itself to be much wider.. the popover could be wider.. or the input itself could expand when you press on it, like the search bar on the list view pages
- More shadow around the popover?

**Comment by mark-prins** [comment]
and some more padding on the bottom of the popover? as well as a shadow?
was wondering if the popover could be wider than the text input - not sure if that would look ok. 

I do like the expand on focus, it might be tricky in this control though, given how much space there is around it. safer to just widen the popover

**Comment by joshxg** [comment]
that all sounds good!
