### ISSUE TITLE
Invoice statuses

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#686]
The current statuses  mechanism isn't really making sense.

This is where I would usually put a suggestion as to what to do here. However, the statuses in general don't make sense to me.. so for now this is a placeholder 😁

**Comment by joshxg** [comment]
OK so it make a little more sense for me to break these up into 4 rather than just two - the statuses for adhoc invoices seem to be different. 

This is my understanding:

Inbound (Stock transfer, automatically created from an outbound):
1. Picked: When the outbound shipment is picked. Read only.
2. Shipped: When the outbound shipment is shipped. Editable, can change to delivered/verified.
3. Delivered: The first status we can change the invoice too.. still editable.
4. Verified: The final status we can change the invoice to - essentially 'finalised' - becomes read only again.

Inbound (Ad hoc, 'new shipment')
1. New - editable, no stock changes when editing things.
- Shipped - N/A?
- Delivered - N/A?
2. Verified: Read only. Stock is updated.

Outbound (Stock transfer, automatically created from a requisition)
- New - When first created from the requisition. Editable [available number of packs adjusted]. Cannot change status until there are no placeholders.
- Allocated - When all placeholders have been allocated. Editable [no placeholder editing].
- Picked - When the stock has been taken from the shelf. Editable. [available AND total packs adjusted]
- Shipped - Stock has been sent for delivery. Read only.
- Delivered - Stock has arrived at the customer. Read only [Status is automatically updated]
- Verified - Stock has been verified by the customer. Read only [Status is automatically updated]

Outbound (Ad hoc, "new shipment")
- New - When first created from the requisition. Editable [available number of packs adjusted]. Cannot change status until there are no placeholders.
- Allocated - When all placeholders have been allocated. Editable [no placeholder editing].
- Picked - When the stock has been taken from the shelf. Editable. [available AND total packs adjusted]
- Shipped - Stock has been sent for delivery. Read only. [Do we show other statuses? What if it is not for a store?)

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/147017343-367c0535-7555-4947-844e-cab063d3f34e.png)

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/147017397-4d078def-355f-4a40-a055-c97f8ddba5f8.png)

**Comment by joshxg** [comment]
So if the above are correct, I'm thinking:

- Add onto `[InvoiceNode]` a field `isAdHoc` or `isStockTransfer`
- Have a different 'set' of statuses for adhoc and stock transfers for the 'crumbs'/'footer thing':
IS-Adhoc: [New, Verified]
IS-StockTransfer: [Picked, Shipped, Delivered, Verified]
OS-AdHoc: [New, Allocated, Picked, Verified]
OS-StockTransfer: [New, Allocated, Picked, Shipped, Delivered, Verified]
- Then, make the button just go to the next in the set

as an aside
- This is confusing. Think two separate statuses for the transport and the actual 'stock' would be better
- This is not whats in the slides Richard did. I wonder if that matters.

**Comment by mark-prins** [comment]
It's possible that `New` might be useful for IS-StockTransfer as well, and the distinction between the dates could give some information to the recipient. was thinking from the point of view of making the list consistent between IS & OS.. though I think there's value in it beyond that.

I'd prefer to have the list of statuses shown in the front end specific to the type of invoice, like you've got. Agree that the applicable list is different for each type. I do think it's ok to mix in the two types (stock status and shipping status) mainly because it's pretty common for it to be done this way, and it's easier to show in the UI like this
