### ISSUE TITLE
Should the side panel open/closed state persist to local storage?

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#694]
Wondering if we should persist the side panel state to local storage similar to the grouped state?

(Also, side note: wonder if we should keep the 'grouped' state *only* in local storage, and not in the table context state? 🤔

**Comment by mark-prins** [comment]
that's a great idea! - I'm always closing it on my laptop! the screen isn't quite wide enough to have it open and show all the column.

and yes, the grouped state isn't required in both, also a good point.
