### ISSUE TITLE
Stocktake add item modal state issues

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#738]
Can I add a couple of extra todos:

- Add item > select item in modal > cancel > Add item : the same item is shown, would be good to clear the state on cancel
- If there is no stock, the form isn’t shown. I think the table should show so that rows can be added manually.. with the mock API, I can't actually add stocktake items!

**Comment by mark-prins** [comment]
@joshxg what are the API bits needed for this one? 
Do you still want to be assigned on it..?

**Comment by joshxg** [comment]
@mark-prins 

I'm pretty sure this was mis labelled and was just some ui state issues which have been sorted in other various prs.. though the modal still likely needs validation similar to inbound
