### ISSUE TITLE
Outbound: Unable to add lines

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#785]
When trying to add lines to an invoice - can't. No items are returned.
Looking at the items query, this is sent with a filter of 

```
{
  "key": "name",
  "filter": {
    "code": {
      "equalTo": ""
    }
  },
  "first": 20,
  "offset": 0
}
```

which may explain why

**Comment by joshxg** [comment]
Heh thanks - just was about to offroad this in my current task 😁

**Comment by mark-prins** [comment]
oh! thanks - can probs just delete this issue then 😁
