### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#787]
The font on this has gone strange too...

<img width="155" alt="Screen Shot 2022-02-09 at 2 49 34 PM" src="https://user-images.githubusercontent.com/9192912/153322585-75747ee1-6d38-4eca-88c6-38a070fe4768.png">

<img width="134" alt="Screen Shot 2022-02-09 at 2 49 43 PM" src="https://user-images.githubusercontent.com/9192912/153322599-6bcd76d5-cda0-45a5-ac1f-3193a570acba.png">

**Comment by joshxg** [comment]
Couple other minors?

The text in the outbound modal has turned all bold:
![image](https://user-images.githubusercontent.com/35858975/153332585-1f623cad-4d1f-4927-8d7b-6b47bcbca601.png)

Theres two codes for an item, one on the LHS of the name, and also below. Maybe just one?
![image](https://user-images.githubusercontent.com/35858975/153332656-3a4c903f-bffc-413a-ba18-e49b2f345fcf.png)
