### ISSUE TITLE
Full screen blocking loading indicator

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#793]
Firstly, I'm not sure this is needed.

What 'this' is: A full screen blocking loading indicator for async actions to prevent the user from touching things. Like mobile.

The use case I am thinking about right now is for changing statuses. If we change to a read-only status, we don't want editing done but if the requests take a little bit of time, it's possible for the user to perform actions which just get reverted. 

Technically, if there is a request processing to change the status and the user changes values, an error will just be thrown and the invoice will get reverted, so likely not a problem.

In general, this isn't too difficult to do and we can essentially just take the mobile implementation which is very nice https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/mSupplyMobileApp.js#L160-L172

**Comment by mark-prins** [comment]
Would be good to have for status changes - my concern is that it's another action which is currently so quick that it might be janky to have a blocking modal. we may have to debounce or extend the display of the blocking indicator, longer than the mutation

**Comment by joshxg** [comment]
I think the confirmation modal is handling the blocking fine. Almost every use case I can think of for a blocking modal would be enhanced by having a confirmation beforehand, so think we can not do this
