### ISSUE TITLE
Item detail page

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#800]
Create an item detail page.
A ton of fields are specified in the requirements spreadsheet:

- Item details headers: item name, item code, store
- General/General
- General/Pricing
- General/Full description
- General/VEN Category
- General/Stock category
- Custom fields
- Storage/Default
- Storage/Restricted to [Location Type]
- Usage
- Stock/Show zero lines
- Log
- Requisitions (huh?)

**Comment by craigdrown** [comment]
@mark-prins  flagging my interest in the "what fields?" discussion when it happens- thanks.

**Comment by joshxg** [comment]
I briefly spoke with richard who had been looking into this. What we spoke about:

([spreadsheet link](https://docs.google.com/spreadsheets/d/1H0Rv1DEOgW0cE07wpfc_KivLf8TcNhYDqlwRp92x-To/edit#gid=0&range=A44))

mSupply form for reference (requisitions tab shows customer requisitions the item was in):
<img width="863" alt="image" src="https://user-images.githubusercontent.com/35858975/153540881-89999cf1-d35c-480d-ab60-e89890c562c0.png">

With an idea of the UI to look something like:
![image](https://user-images.githubusercontent.com/35858975/153540930-4a979638-ea4a-4f5f-8d5d-8bdaa47de8d4.png)

- A 'quick summary' section (top of the image)
- Tabs for each of the 'tabs' in the mSupply view. (that we want to add)

**Comment by andreievg** [comment]
Sounds great, is this in v1 ? 

Should item have these resolvers ? :

* invoices
* requisitions

(we can add filters to invoice->lines(filter), and requisition.lines(filter))

**Comment by joshxg** [comment]
> Sounds great, is this in v1 ?
> Should item have these resolvers ? :

Some version of the page. Though, what that page actually shows is not locked in yet

**Comment by mark-prins** [comment]
Mock data available in [PR#965](https://github.com/openmsupply/remote-server/pull/965)

**Comment by mark-prins** [comment]
there is much to be done.. in another issue though. the basic detail page is in.
