### ISSUE TITLE
Printing of shipments.

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/openmsupply-client#806]
At the very least we need to be able to print the following
* Outbound shipment
  * pick list
  * pack list
  * invoice
* Inbound shipment
  * invoice

**Summary**
* There is a print button 
*  (either nearby or in a new window) there a list of available print forms for that type of invoice - there is a default form. The 
* only PDFs are generated.
* On choosing a form, POST to an endpoint the form name (possibly its type) and the ID of the invoice to print. 
* Back end sends back a PDF.

**Comment by joshxg** [comment]
- hard coded list of available forms, for now? (use prefs or something later)
- the language used implies the use of rest on the backend over graphql (for one round trip rather than two)?

**Comment by mark-prins** [comment]
the basic implementation is done. the list of available forms is outside of the control of this team
