### ISSUE TITLE
Implement API for creating/updating placeholder rows

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#810]
We have the ability to change placeholder rows currently. However, when saving, we don't actually create/update placeholder rows correctly.

We should be using `insertOutboundShipmentUnallocatedLine` // `updateOutboundShipmentUnallocatedLine` mutations. 

At the moment, when we save/close/ok the outbound edit modal, we use the `batchOutboundShipment` mutation. However, the `batchOutboundShipment` mutation does not support unallocated line mutations.

I would like to do this but likely it's best to ask the backend team to implement this into `batchOutboundShipment`

**Comment by andreievg** [comment]
Should be in develop now
