### ISSUE TITLE
Add related document links to invoice pages

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#862]
`InvoiceNode` now has some fields for related documents: `linkedShipment` and `requisition` which can be linked to from the `related documents` section of the side bar

**Comment by joshxg** [comment]
@mark-prins 

Realising that it was talked about that we want to actually be able to press a button and go to the ‘related document’, right? i.e. click on the linked shipment for an outbound and actually go to the URL for the shipment? 

- For a store on the same site we can do this [Though, we would need the store in the url and the api changes for that]
- For a store on a different site, would we want to link to...?

**Comment by joshxg** [comment]
I realised that with the new sync system we would actually have copies (though potentially stale) of the related records to link to.

However, because the stores won't be active on the site, the API will block querying for them.

We can access the linked records through nested fields.. i.e. on `Invoice` there is a `linkedShipment` field.

I had assumed we would just want to load the normal detail view (though disabled), so it would be *a lot* easier to have the query work 🤷 

I guess I need to confirm what exactly the requirement is here rather than assuming

**Comment by mark-prins** [comment]
yes - I was hoping that we could just fetch the related document from the API. 

That is a problem if the store isn't active on the site, and we still need the changes to support the store in the URL. Not at all keen on using the `linkedShipment` to get the data to populate a read-only view of a record.

Will need to consult about the _actual_ requirement

**Comment by richardmoizeau** [comment]
already replied on Telegram but here are the requirements:
1) as a user, I can check what are the related documents (or transactions) of a transaction:

- Customer: I look at a request requisition and I can see the references of inbound shipments that has been created against it
- Customer: I look at an inbound shipment and I can the reference of the request requisition it originates from
- Supplier: I look at a response requisition and I can see the reference of outbound shipments created against it

2) if I want to know the details of the related document, I should be able to click on it and it would open the detailed view of the transaction. 

Hope it helps :-)

**Comment by joshxg** [comment]
Thanks @richardmoizeau 

I had a wrong assumption 😁 

So, these are NOT use cases:

- Customer: I have a request requisition and I can view the suppliers response requisition
- Supplier: I have an inbound shipment and I can view the customers outbound shipment

It is ONLY documents for your store?

**Comment by richardmoizeau** [comment]
Yes, it is a link for docs in your store. 
The other thing we could do in the detail panel, general info, is to have something called Supplier Reference(s) and the reference of the requisition response could appear here. But no link to it though.

**Comment by joshxg** [comment]
Ah ok, so I completely overcomplicated this:

- Inbound: The linked Supplier requisition
- Outbound: The linked Customer requisition
- Response: The linked Outbounds
- Request: The linked inbound

Super easy!
