### ISSUE TITLE
Autocomplete caret has jumped over the fence to the other side

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#886]
The little caret arrow icon of the autocomplete component has jumped onto the left hand side!

![image](https://user-images.githubusercontent.com/35858975/155253202-a72317d3-b9a3-4451-a9c6-81d39cdb23d0.png)
![image](https://user-images.githubusercontent.com/35858975/155253208-9bdbf2e8-5899-4bad-88be-69b19b1e037d.png)

What's that about?

**Comment by mark-prins** [comment]
I noticed that on the login screen too! Not consistent or reproducible though.. 🤔

**Comment by mark-prins** [comment]
Something funky with rtl

![Screen Shot 2022-02-24 at 8 56 53 AM](https://user-images.githubusercontent.com/9192912/155398162-08bf553e-f061-4315-a562-99bb1a06120a.png)

**Comment by mark-prins** [comment]
cannot repro now
