### ISSUE TITLE
Dashboard: Show number of items with low MOS

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#892]
Unsure what 'low' is in this context. 3 months for now?
Is it possible to use the `items` query to start with?

**Comment by joshxg** [comment]
could have a drop down for the min months of stock and use that as a multiplier using `averageMonthlyConsumption` and `availableStockOnHand` from the `stats` field from `ItemNode`..

A step further would be to see if we can get a mutation `createAutomaticRequestRequisition(minMonthsOfStock, requisitionId?)` which can create a request requisition with all stock with less than the threshold (the optional requisitionId is for also putting the button in the detail view of a request requisition)
