### ISSUE TITLE
Sync settings

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#909]
For now, mSupply:

Tables:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/35858975/155836110-8b27b33a-0734-4e7a-b34e-844bd1c2fca9.png">

<img width="183" alt="image" src="https://user-images.githubusercontent.com/35858975/155836146-ab9d8bed-91f5-4d97-bff6-d19300a19fbb.png">

UI:
![image](https://user-images.githubusercontent.com/35858975/155836163-9888c0db-8e37-4907-9969-bb43a3a962e8.png)

Requirements (unconfirmed, starting discussion):
- Edt sync name, password, central server URL [Maybe: site code, batchsize, interval

Other possibilities:
- site type
- filter for site ID on `stores`
- Add/remove store mutations?
- Check connection button?
- Number of sync records waiting
- indication of sync in progress [probably not - likely want to use ws]

![image](https://user-images.githubusercontent.com/35858975/156079133-2530b2e4-00f7-4c15-8615-c920303fa602.png)

**Comment by Chris-Petty** [comment]
UI notes:
- Until you can look at all sites on a remote, this the mSupply UI is a bit overkill. Or at least you could get away with a lot less (i.e. I think your initial requirements about do it). Did consider doing 2 forms for 4D mSupply, on for central and one for remote, but there was a fair bit of code overlap.
  - The main thing is that the `site` table doesn't sync. If you have a store list and store view/page thingy, then that's got at least as much data as the list of stores on the `[site].input` pic you have there.
  - So add/remove store mutations, nah. Not till the new app is doing central server configurations.
- A "sync now" button would do everything check connection button does, but happen to start sync process proper too.

Schema notes:
- Site fields you'll probably use: site_ID, name, password, code (Maybe, this isn't actually used for anything but UI, unlike the other 3). The rest are either central server stuffs or unused
- You can probably ignore the node http client boolean, that just a 4D desktop thang
- A user settable batch size is handy, but fwiw dynamic batch size (like in mobile) results in waaaaaaaaay faster syncing (at a certain threshold, the gzip compression of larger batches should actually make the overall bandwidth used lower...)

**Comment by mark-prins** [comment]
Mostly done with #1193 so will close this one for now.
