### ISSUE TITLE
Placeholder row indication

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#923]
Currently there is no indication a row is a plceholder row in the list of items.

mSupply has each row highlighted red. What should we do?

**Comment by joshxg** [comment]
Going to add some sort of background or something .. some styling change to a row.

Essentially a new concept to implement of dynamically changing row styles, as I don't particularly want to check the generic row data within `DataRow`.

I'm thinking to use the `TableStore`. In addition to the current row states: `isSelected`, isExpanded`, `isDisabled`, an `extraStyles` that can hold some styling that will be applied.. 🤔

**Comment by mark-prins** [comment]
The only design mock up that I remember has the placeholder as red text

![Screen Shot 2022-03-02 at 3 27 48 PM](https://user-images.githubusercontent.com/9192912/156283103-cd9b8eff-c740-4c92-8653-461767eb1809.png)

I think red is more of an error indication though. Perhaps blue?

In the absence of guidance though - some sort of styling in the `TableStore` sounds perfect.
