### ISSUE TITLE
Put money symbol outside of inputs

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#926]
https://github.com/openmsupply/openmsupply-client/pull/915#discussion_r816428000

**Comment by joshxg** [comment]
@mark-prins do you still have the branch with the styles you did with the currency symbol outside of the input?

**Comment by mark-prins** [comment]
I just did a quick hack, took a screenshot and dumped it. Will have a look at it though.. undecided now whether it's a good idea or not

**Comment by joshxg** [comment]
Oh yup. I wasn't sure how to do the numeric input one especially. It looked like the symbol was inside the input but on the right of little incr/decr buttons and thought there was some special html/css thing?

If it's just a minor tweak and you don't feel strongly I'll concentrate on other issues!

**Comment by mark-prins** [comment]
nah, don't feel strongly. let's just quietly close this one for now..
