### ISSUE TITLE
query key factories for maintainability

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#931]
Currently we're *generally* inlining query keys.

I've already come up against a couple of bugs where I've miss copy pasted a query key and/or mis-typed.

It would be good to have a strong pattern for query keys to:

- Avoid mistyping / using the wrong key
- Easily able to determine at what level in the hierarchy we can invalidate, at
- Easily use the query keys

One way is to use a global query key file/folder, with all the query keys, so that we can easily view all query keys. This would also stop accidentally using a query key the same as another feature.

However, I think colocation next to where the queries are used is generally better all round.

I am thinking to have something like this in the `useXXApi` hook:

```
const keys = {
  base: () => [ 'requisition', storeId ],
  detail: (id) => [ ...keys.base(), id ],
  list: () => [ ...keys.base(), 'list' ],
  listWithParam: (params) => [...keys.list(),  params ],
}
```

Then when we use the api..

`useQuery(api.keys.detail(id), () => api.get.byId(id))`

**Comment by mark-prins** [comment]
that is a neat idea. Agree with colocation - the operations and api are colocated too, so that makes sense.
