### ISSUE TITLE
The disabled state of a row should be passed onto the cells

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#933]
Currently we don't disable editable cells for anything.

We should! - finalised etc.

The `DataRow` component has a disabled state which can be set via the table context.

We should pass the disabled state to the cells, by adding `isDisabled: boolean` to the `Cell<T>` type, and then within each cell component, handle the disabled state

**Comment by joshxg** [comment]
A tricky cell to show as disabled is the `color` picker in the list view. What I would think is the disabled state is just the default colour gray/grey/grerey

**Comment by mark-prins** [comment]
for the colour picker - I think just remove the action and have the cursor as standard 🤷
