### ISSUE TITLE
Put the query parameters for items/lists in a more accessible place

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#936]
The hooks `useInboundItems` / `useInboundLines` / `useInbounds` etc have a `useQueryParams` per instance.

So, if you're to call `useInbounds` in two places, the underlying data (the queried inbound shipments) can be the same (if the query params are the same, as that is in the query key), however if you have the query params for one instance of the hook, this does not effect the other.

i.e.

```
const { data: d1, onSortBy: sortD1 } = useInbounds()
const { data: d2, onSortBy: sortD2 } = useInbounds()

console.log(d1 === d2) // This is true

sortD2('key') // After this call, the above will log false, as d2 is a new set of data and d1 is not updated.
```

We can fix this by having the query parameters and controllers live in for example, zustand state, the URL or context.

This isn't so much of a problem right now and could potentially be left as these hooks aren't called all that much.

My preference would be to have a single source of truth for the query parameters in the URL as that also solves the URL issue

**Comment by mark-prins** [comment]
Fixed with #1204
