### ISSUE TITLE
Internal order - stock distribution bar

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#957]
For internal orders, when adding or editing an item, the suggested quantity is explained using a bar like this:

![Screen Shot 2022-03-04 at 9 19 48 AM](https://user-images.githubusercontent.com/9192912/156646388-baabedc3-6ee8-4dcb-a4d2-a305c926cac3.png)

We don't have values for 'on order' or in-transit at this stage, so we should leave that for later.

**Comment by joshxg** [comment]
Maybe we could give the backend team a shape to implement - I think it would be helpful for them. Would this work?

a mutation `itemChartData(from with default)` which is queried for when we open the modal with:

```
{
    suggestedQuantity:  { soh: number, onOrder: number, suggested: number, inTransit: number },
    consumptionHistory: { amc: number, movingAverage: number, date: string }[],
    stockEvolution: { date: string, projected: number  }
}
```

**Comment by mark-prins** [comment]
> Maybe we could give the backend team a shape to implement - I think it would be helpful for them. Would this work?

Yeah - that's very nice. We can get by for now with the `itemStats` (for AMC) and `suggestedQuantity` on `RequisitionLineNode` - enough to get a basic bar in anyway.
