### ISSUE TITLE
Outbound / Stocktake edit modals disabled state.

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#984]
Both outbound and stocktake edit modals show all stock lines for these edit modals, allowing the user to pick to issue or count from any.

When these modals are in a finalised state, this doesn't make sense.

So:
1. Disable opening the edit modals when a document is disabled
2. Show only the lines in the document in the edit modal

**Comment by joshxg** [comment]
@mark-prins 

What do you think about disabling opening of the edit modal when the document is in a 'finalised' state (is disabled with no more editing)?

If yes, then this is pretty easy! If no, then would need to look at changing up the outbound/stocktake modals. The outbound for example will still show all stock lines and also the columns might not make sense. I.e. the 'available stock' column on an outbound comes from the stock line so won't be too helpful!

**Comment by mark-prins** [comment]
yeah, let's just disable. We lose a little bit of information but not enough to make it worth going too deep with disabling etc.

if the loss of pricing on stocktakes, for example, is real bad then we could create a new read only modal and use that instead

**Comment by joshxg** [comment]
Cool.

I would have assumed all the columns would have been in the table, anyway. But.. if I actually look, that's not the case. But I wonder if that is just something that should be done.

i.e. stocktakes has pretty low amount of info at the moment:
![image](https://user-images.githubusercontent.com/35858975/157336503-1f0951ba-79dd-44ff-a093-51aa8b9d17be.png)

**Comment by mark-prins** [comment]
maybe adding the `location` column? don't think we need pricing though
