### ISSUE TITLE
Statuses for manually created inbounds are a little odd, you'll never guess why

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/openmsupply-client#995]
Manually created don't utilise these statuses:

![image](https://user-images.githubusercontent.com/35858975/157339948-94292d34-28b7-4243-9e7d-d7023daf0310.png)

Looks a bit odd! Maybe remove them for manually created ones?

**Comment by mark-prins** [comment]
I agree - it does. we should remove them 😃

**Comment by joshxg** [comment]
Possibly could make the only thing editable on an inbound when the status is shipped be the status.

So the status is "shipped" and when you set it to "delivered", you can start editing lines etc
